Probesys/bileto

assets/stylesheets/components/buttons.css, assets/stylesheets/components/forms.css, assets/stylesheets/components/icons.css, src/Utils/Time.php, tests/Utils/TimeTest.php
- Enlarge the size of buttons borders
- Improve the size of the select elements
- Decrease the size of the icons
- (tec) Provide a Time class
1. Check that buttons borders are slightly larger than before
2. Check that selects height matches the height of inputs
3. Check that icons are slightly smaller
=> imp: various improvements

assets/stylesheets/components/forms.css, templates/organizations/tickets/new.html.twig, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
- Change the label "What's the issue?" to "Title"
- Add padding to labels
1. Check the label has been changed in the new ticket form
=> Fix wording of the ticket title label (+ improve labels padding)

assets/stylesheets/application.css, assets/stylesheets/components/timelines.css, src/Controller/Tickets/MessagesController.php, src/Controller/TicketsController.php, src/Entity/Message.php, templates/organizations/tickets/new.html.twig, templates/tickets/messages/_messages.html.twig, templates/tickets/show.html.twig, tests/Controller/Organizations/TicketsControllerTest.php, tests/Controller/Tickets/MessagesControllerTest.php, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml, translations/validators.en_GB.yaml, translations/validators.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/38
- Add a tickets/messages controller to create messages associated to a ticket
- Add a form at the bottom of the list of messages
- Extract the list of messages + form in a partial view
2. Open the ticket and write an answer
3. Check it appears at the bottom of the list (and that the scroll is not reset)
=> new: Allow to answer to a ticket

assets/stylesheets/application.css, assets/stylesheets/components/tables.css, assets/stylesheets/components/text.css, src/Controller/Organizations/TicketsController.php, src/Entity/Organization.php, src/Entity/Ticket.php, templates/organizations/tickets/index.html.twig, tests/Controller/Organizations/TicketsControllerTest.php, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/15
- List the tickets in a table
- Sort tickets by createdAt (desc)
- Don't list resolved and closed tickets
1. go to the list of tickets
2. create a bunch of tickets with different statuses
3. check that resolved and closed tickets are not listed
4. check they are sorted from the newest to the oldest
=> imp: Improve the list of tickets

assets/stylesheets/components/buttons.css, src/Controller/Tickets/ActorsController.php, templates/tickets/actors/edit.html.twig, templates/tickets/show.html.twig, tests/Controller/Tickets/ActorsControllerTest.php, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/40
- Add a button next to the "actors" section to change them
- Add a form to edit requester and assignee
1. Open a ticket, click on the "edit" button of the actors
2. Change the requester and assignee and save the form
3. Check they've changed on the ticket page
=> new: Change requester and assignee of a ticket

assets/stylesheets/_colors.light.css
- Change the color of grey3 with the correct value from Radix UI
=> fix: Fix the color grey3

README.md, assets/javascripts/controllers/modal_opener_controller.js, assets/javascripts/controllers/popup_controller.js, assets/stylesheets/components/layout.css, docs/developers/modals.md, docs/developers/popups.md, templates/base.html.twig, templates/tickets/show.html.twig, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Changes proposed in this pull request: see commits
1. disable javascript
2. verify a banner is shown at the top of the page
=> imp: Various small improvements

assets/stylesheets/components/popups.css
Related to https://github.com/Probesys/bileto/issues/128
- decrease the width of the border of popup menu
- increase the contrast of the border of popup menu
- add an arrow at the top of the popup menu
- increase the width of the popup items to 100% of the menu
- remove the border of the popup items
1. Open a popup
2. Verify it looks better
=> imp: Improve the look of the popups

assets/stylesheets/components/buttons.css, assets/stylesheets/components/popups.css, src/Controller/Organizations/TicketsController.php, src/Controller/Tickets/ActorsController.php, src/Service/ActorsLister.php, templates/organizations/tickets/new.html.twig, templates/tickets/actors/edit.html.twig, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/139
- Put the current user at the top of actors list
- Add "(yourself)" label to the current user's email in the select boxes
- Fix glitches on some buttons because of the new disabled style
1. Open a ticket
2. Verify that your current user is at the top of the list and that "(yourself)" appears
3. Edit actors of the ticket, do the same verifications
=> imp: Improve order of actors lists

docs/maintainers/release.md
- Add a section to publish the release on GitHub
- Add a section to fix mistakes during the release
- Add a dash at the start of git logs 
How to test the feature manually: N/A
=> doc: Complete the documentation to release new versions

README.md, assets/javascripts/application.js, assets/javascripts/controllers/notifications_controller.js, assets/stylesheets/application.css, assets/stylesheets/components/notifications.css, docs/developers/notifications.md, src/Controller/Tickets/TypeController.php, templates/base.html.twig, tests/Controller/Tickets/TypeControllerTest.php, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/132
- create a notification system based on flash messages
- add error messages to the Tickets\Type controller
1. change the csrf token value of the "Change to incident" button in the DOM with devtools
2. check a notification appears
=> tec: Notify when "update ticket type" fails

migrations/Version20230103104502AddNameToUsers.php, src/Controller/ProfileController.php, src/Entity/User.php, templates/base.html.twig, templates/organizations/tickets/index.html.twig, templates/organizations/tickets/new.html.twig, templates/profile/edit.html.twig, templates/tickets/actors/edit.html.twig, templates/tickets/show.html.twig, tests/Controller/ProfileControllerTest.php, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/89
- Add a "name" field to User
- Add a Profile page to edit name and email
- Show the "display name" (name or email) of users instead of email in the interface
1. Go to the "profile" page
2. Change your email and name
3. Check the name is used in the user menu and in the tickets interface
=> new: Edit user profile

assets/stylesheets/_colors.dark.css, assets/stylesheets/_colors.light.css
- Change primary color from Blue to Teal
- Indicate the name of the colors scales
1. Open Bileto, verify it uses the Teal color scale
=> imp: Change the primary color scale

composer.lock, package-lock.json
=> tec: Update dependencies

docs/developers/roles.md, src/Controller/RolesController.php, templates/roles/_role_form.html.twig, templates/roles/edit.html.twig, templates/roles/index.html.twig, tests/Controller/RolesControllerTest.php, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/88
- Extract the "new role" form in a partial to be reused during edition
- Add edit and update endpoints to change a role
1. Go to the roles page
2. Edit a role
3. Check it is correctly updated
=> new: edit roles

assets/stylesheets/application.css, assets/stylesheets/components/lists.css, src/Controller/UsersController.php, src/Entity/Role.php, src/Service/UserSorter.php, templates/_sidebar_settings.html.twig, templates/roles/_permission_checkbox.html.twig, templates/roles/_role_form.html.twig, templates/settings/index.html.twig, templates/users/index.html.twig, tests/Controller/UsersControllerTest.php, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/114
- Create a CSS `list` component
- Create the `admin:manage:users` permission
- Add a page to list users (controller + template)
- Sort users by their display name (add the `UserSorter`)
1. Go to the settings > "Users" section
2. Check you can see the users
=> new: List users

src/Controller/UsersController.php, templates/base.html.twig, templates/users/index.html.twig, templates/users/new.html.twig, tests/Controller/UsersControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/114
- Add endpoints and views to create users
1. Go to the "users" section
2. Create users with and without a name
3. Check it works
=> new: Create users

README.md, config/services.yaml, docs/developers/entity.md, migrations/Version20230214161800AddMetaFieldsToMessageOrganizationAndUser.php, src/Command/Users/CreateCommand.php, src/Controller/Organizations/TicketsController.php, src/Controller/OrganizationsController.php, src/Controller/RolesController.php, src/Controller/Tickets/MessagesController.php, src/Controller/UsersController.php, src/Entity/Authorization.php, src/Entity/Message.php, src/Entity/MetaEntityInterface.php, src/Entity/Organization.php, src/Entity/Role.php, src/Entity/Ticket.php, src/Entity/User.php, src/EntityListener/EntitySetMetaListener.php, src/Repository/AuthorizationRepository.php, src/Repository/MessageRepository.php, src/Repository/OrganizationRepository.php, src/Repository/RoleRepository.php, src/Repository/TicketRepository.php, src/Repository/UidGeneratorInterface.php, src/Repository/UserRepository.php, tests/AuthorizationHelper.php, tests/Factory/MessageFactory.php, tests/Factory/OrganizationFactory.php, tests/Factory/UserFactory.php
https://github.com/Probesys/bileto/issues/208
- add `uid`, `createdAt` and `createdBy` fields when missing
- move the code that set these fields to the `EntitySetMetaListener` class
- make the entities implement the `MetaEntityInterface` interface
- make the repositories implement the `UidGeneratorInterface` interface
- add documentation about declaring new entities
- use the application normally, everything should work as before
=> tec: Refactor Entities "meta" fields

config/services.yaml, src/EntityListener/EntitySetMetaListener.php
https://github.com/Probesys/bileto/issues/208
- Use `AsEntityListener` attribute instead of tagging `EntitySetMetaListener` in the configuration
N/A
=> misc: Clean EntitySetMetaListener a bit

assets/stylesheets/application.css, assets/stylesheets/components/events.css, docs/developers/entity.md, migrations/Version20230215153215CreateEntityEvent.php, src/Controller/Tickets/MessagesController.php, src/Controller/TicketsController.php, src/Entity/ActivityRecordableInterface.php, src/Entity/Authorization.php, src/Entity/EntityEvent.php, src/Entity/Message.php, src/Entity/Organization.php, src/Entity/Role.php, src/Entity/Ticket.php, src/Entity/User.php, src/EventSubscriber/EntityActivitySubscriber.php, src/Repository/EntityEventRepository.php, src/Service/TicketTimeline.php, templates/tickets/_timeline_event.html.twig, templates/tickets/_timeline_message.html.twig, templates/tickets/show.html.twig, tests/Controller/TicketsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/19
- Create a EntityEvent entity / table to store the activity of the entities
- Make the other entities activity recordable (via a new interface)
- Create a Doctrine Lifecycle Subscriber to record the activity of the entities
- Merge ticket messages and events in a same timeline, and display events
- Create a ticket, and change a few things (e.g. title, status, priority, etc.)
- Check the events appear in the ticket timeline
=> new: Ticket activity

migrations/Version20230217142448AddIndexOnEntityEvent.php, src/Entity/EntityEvent.php, src/Twig/TicketEventChangesFormatterExtension.php, templates/tickets/_timeline_event.html.twig, tests/Twig/TicketEventChangesFormatterExtensionTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/19
- create a Twig extension to format Ticket events based on the modified field
- add an index on EntityEvent (entityType, entityId)
- make a bunch of changes in a ticket → check the events are coherent and comprehensible
=> imp: Improve format of events

assets/stylesheets/components/events.css
N/A
- decrease the size of events messages
- keep the hour on the same line than the messages
- open a ticket with events → check size of events is slightly smaller
=> imp: Decrease size of events messages

src/Service/TicketTimeline.php, src/Utils/Timeline.php, templates/tickets/show.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/222
- Extract a Timeline object to be able to access items of different types in the templates
- Add the number of messages in the ticket view
1. Go to a ticket → check the number of messages is displayed in the header of the ticket
=> imp: Display the number of messages in tickets

assets/stylesheets/components/events.css, assets/stylesheets/components/messages.css, assets/stylesheets/components/timelines.css
N/A
- Hide (i.e. display none) avatars in tickets on small screen
- move the timeline bar + events on the left on small screen (5rem less)
- slightly realign the "hide history" icon on the timeline bar
- open a ticket on a small screen
- check everything is correctly aligned
=> imp: Hide avatars in tickets on small screen

templates/base.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
N/A
- Change the logo alt text from "Bileto" to "Home"
- Start a screen reader and give the focus to the logo
- Check the screen reader announces "Home"
=> a11y: Change the logo alt text

assets/stylesheets/application.css, assets/stylesheets/components/events.css, assets/stylesheets/components/layout.css, assets/stylesheets/utils/rows.css, src/Controller/Organizations/TicketsController.php, templates/organizations/tickets/new.html.twig, tests/Controller/Organizations/TicketsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/116
https://github.com/Probesys/bileto/issues/148
https://github.com/Probesys/bileto/issues/243
- Change flex-grow by flex property
- Set pointer cursor on <summary> elements
- Put renamed tickets titles between quotes
- Add a "type" field to the "new ticket" form
- Add priority fields to the "new ticket" form
- Hide fields of this form based on the permissions given to the user
- go to the "new ticket" form with full permissions → check that you can choose the type and the priority of the ticket
- go to the "new ticket" form with only the "Create tickets" permission → check that you can only choose a title and add a message
=> imp: Improve the form to open tickets

README.md, ROADMAP.md
https://github.com/Probesys/bileto/issues/238
- fix few things in the readme
- add a roadmap file
- read the roadmap :shrug:
=> doc: Add a roadmap

templates/tickets/show.html.twig
N/A
- change the ellipsis icon by the char "—" next to the diff day in the timeline
N/A
=> imp: Improve the look of the diff days in the timeline

Makefile
N/A
- Add more linters related to Symfony to `make lint` (container, twig and yaml of translations)
- execute `make lint` → check it passes
=> tec: Lint more things (containers, twig and translations)

src/Controller/Organizations/TicketsController.php, src/Controller/Tickets/ActorsController.php, templates/organizations/tickets/new.html.twig, templates/tickets/actors/edit.html.twig, tests/Controller/Organizations/TicketsControllerTest.php, tests/Controller/Tickets/ActorsControllerTest.php
N/A
- change `requesterId` and `assigneeId` parameters by `requesterUid` and `assigneeUid`
- create a ticket → check it creates it with correct the requester and assignee
- update the actors of a ticket → check it changes with correct the requester and assignee
=> tec: Use User uid instead of id in actors forms

docs/developers/search-engine.md, src/Controller/Organizations/TicketsController.php, src/Controller/PagesController.php, src/Controller/TicketsController.php, src/SearchEngine/TicketSearcher.php, templates/organizations/tickets/index.html.twig, templates/tickets/_search_form.html.twig, templates/tickets/index.html.twig, tests/SearchEngine/TicketSearcherTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/8
See commits
N/A
=> tec: Refactor search code

assets/javascripts/application.js, assets/javascripts/controllers/checkboxes_controller.js, assets/stylesheets/application.css, assets/stylesheets/components/buttons.css, assets/stylesheets/components/popups.css, assets/stylesheets/utils/flow.css, assets/stylesheets/utils/indent.css, assets/stylesheets/utils/rows.css, docs/developers/popups.md, docs/developers/rows-and-grids.md, src/Entity/Ticket.php, templates/base.html.twig, templates/tickets/show.html.twig
=> tec: Improve components

templates/roles/_role_form.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/274
- add 2 buttons above the roles form to check/uncheck all the checkboxes
- create or update a role
- click on "check all" and "uncheck all" → check it selects and unselect all the checkboxes
=> imp: Allow to (un)check all the roles at once

config/packages/security.yaml, migrations/Version20230510072432CreateRememberMeToken.php, templates/login/new.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/282
- enable "remember me" in the security config
- add a checkbox to the login form
- store the tokens in database and create the corresponding table
- go to the login form
- login by checking "remember me"
- check that a cookie named "REMEMBERME" is present in your browser and that it is valid for 30 days
=> imp: Add a “remember me” checkbox to the login form

templates/base.html.twig, templates/login/new.html.twig
https://github.com/Probesys/bileto/issues/289
- add `data-turbo="false"` on login and logout forms
Follow steps of https://github.com/Probesys/bileto/issues/289 and check the behaviour is correct.
=> fix: Use the correct color scheme after login or logout

src/Controller/OrganizationsController.php, templates/organizations/_organizations_as_list.html.twig, templates/organizations/edit.html.twig, templates/organizations/index.html.twig, templates/pages/home.html.twig, tests/Controller/OrganizationsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/18
- create a form to edit organizations name
- add a link to this form in the admin
- go to the settings > organizations and click on an orga
- change the name and submit
- check you're redirected to the list and that the name has changed
=> new: Allow to rename the organizations

migrations/Version20230511091245SetDeleteCascadeOnOrgaConstraints.php, src/Command/SeedsCommand.php, src/Controller/OrganizationsController.php, src/Entity/Authorization.php, src/Entity/Message.php, src/Entity/Ticket.php, src/Repository/AuthorizationRepository.php, src/Repository/OrganizationRepository.php, templates/alerts/_alert.html.twig, templates/organizations/_organizations_as_admin_list.html.twig, templates/organizations/deletion.html.twig, templates/organizations/index.html.twig, tests/Controller/OrganizationsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/18
- change the constraints on organization relations to delete in cascade
- provide a "deletion" form to delete an organization and its sub-organizations
- go to the organizations admin
- click on "delete" of an organizations (ideally with sub-organizations, tickets and authorizations)
- confirm the deletion
- check the organization no longer exists
- in DB, check that the associated relations no longer exist either
=> new: Allow to delete the organizations

src/Controller/Organizations/TicketsController.php, src/Controller/TicketsController.php, src/SearchEngine/TicketSearcher.php, templates/organizations/tickets/index.html.twig, templates/tickets/_sort_button.html.twig, templates/tickets/index.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/117
- accept a "sort" parameter in the TicketSearcher::getTickets method
- add a "sort button" above the lists of tickets, i.e. a popup menu allowing to select the sort
- go to a list of tickets
- select a sort option
- check it matches with what was expected
=> imp: Allow to sort the lists of tickets

templates/organizations/tickets/index.html.twig, templates/tickets/index.html.twig
https://github.com/Probesys/bileto/issues/117
- replace the currentPath query from `query=` to `q=`
- change the filters in the search form
- change the sort option
- check that the filters are still applied
=> fix: Remember the query when changing the sort option

src/Entity/Authorization.php, src/Entity/Message.php, src/Entity/Organization.php, src/Entity/Role.php, src/Entity/Ticket.php, src/Entity/User.php, templates/users/new.html.twig
https://github.com/Probesys/bileto/issues/291
- remove the UniqueEntity constraint from the uid fields (i.e. it was useless)
- remove the required attribute from the user name input
N/A
=> tec: Remove UniqueEntity constraint from uid fields

.github/workflows/linters.yml, .github/workflows/tests.yml, README.md, translations/errors+intl-icu.en_GB.yaml, translations/errors+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/290
- enable the tests for PHP 8.2 on the CI
N/A
=> tec: Add support for PHP 8.2

.env, .github/workflows/tests.yml, README.md, docker/docker-compose.yml, docs/administrators/deploy.md, env.sample, tests/Controller/Organizations/TicketsControllerTest.php
https://github.com/Probesys/bileto/issues/292
- change versions in env files, CI file, docker-compose.yml and documentation
N/A
=> tec: Add support for PGSQL 11+ and MariaDB 10.4+

.env, docs/developers/greenmail.md, env.sample, src/Command/SeedsCommand.php, src/Repository/MailboxRepository.php, templates/base.html.twig, tests/Command/SeedsCommandTest.php
N/A
- use `app.locale` instead of `app.request.locale` in the templates
- change the SMTP "From" sender to `support@example.com`
- refactor the declaration of services in the Seeds command
- add the `FindOrCreateTrait` to the `MailboxRepository`
- create a mailbox in the seeds so there is a default one when starting developing
- answer to a ticket → check that the sender of the notification is `support@example.com`
- run `make db-reset FORCE=true` → check that a default `support@example.com` mailbox is created and that the connection works
=> tec: Various improvements

docs/developers/email-collector.md, src/Entity/MailboxEmail.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/Notifier/NewMessageNotification.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
https://github.com/Probesys/bileto/issues/36
- change the notification subject to add square brackets around the ticket ID (to improve parsing)
- extract a ticket ID from the email subject and load the corresponding ticket
- notify ticket actors when a new answer is added by email
- with the address of a normal Bileto user, send an email to `support@example.com`
- collect the emails and check that a new ticket is created
- with a tech user, assign yourself to the ticket and write an answer
- check that an email is sent to the normal user
- answer to the email
- check that the answer is added to the ticket and that an email is sent to the tech user
- with the address of the tech user, answer to the email
- check that the answer is added to the ticket and that an email is sent to the normal …
=> new: Allow to answer to a ticket by email

migrations/Version20230623081500SetDeleteCascadeOnMailboxEmailMailbox.php, src/Controller/MailboxesController.php, src/Entity/MailboxEmail.php, templates/mailboxes/index.html.twig, tests/Controller/MailboxesControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
- add a controller to delete mailboxes
- add `DELETE CASCADE` on MailboxEmail->mailbox
- add a button on the mailboxes list to delete a mailbox
- in the admin, create a mailbox
- delete the mailbox → check it doesn't appear anymore
=> new: Allow to delete mailboxes

composer.lock, package-lock.json
https://github.com/Probesys/bileto/issues/342
N/A
N/A
=> tec: Update the dependencies

Makefile
N/A
- refactor the docker-compose commands in the Makefile
- stop the worker container before reseting the db, and restart it after
- run `make db-reset FORCE=true` → check it works
=> fix: Fix the make db-reset command

src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
https://github.com/Probesys/bileto/issues/36
- when processing emails, consider the organization of the ticket instead of the one of the user
- answer to an email with an address which can answer in its organization (different from the one of the ticket) → check the email is not accepted
=> fix: Fix permissions when answering to a different organization

docs/developers/email-collector.md, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
https://github.com/Probesys/bileto/issues/43
- don't set createdAt of tickets and messages when processing the emails 
- send an email from a server with a different time to the web server → check that the message is created at Bileto time
=> imp: Use the current date instead of the email date

src/Controller/PreferencesController.php, src/Controller/ProfileController.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
N/A
- add a "success" flash at the end of Profile and Preferences update controllers
- submit the profile form → check that a successful notification is shown
- submit the preferences form → check that a successful notification is shown
=> imp: Show a notification when profile/preferences are saved

src/Controller/UsersController.php, templates/users/edit.html.twig, templates/users/index.html.twig, tests/Controller/UsersControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/340
- add a form to edit users
- add a link to the form in the users list
- go to the users list
- edit a user → check that your changes are saved
=> new: Allow to edit users

assets/stylesheets/components/notifications.css, templates/base.html.twig
N/A
- put the notifications on the right
- add bolder border on the left
- make the close button more discreet
- decrease the font size
- disable pointer-events on the notifications wrapper
- test the connection / save your preferences → check the notification message looks better
=> imp: Improve the look of the notifications

src/Controller/MailboxesController.php, src/Repository/MailboxEmailRepository.php, templates/mailboxes/index.html.twig, tests/Controller/MailboxesControllerTest.php, tests/Factory/MailboxEmailFactory.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
- add a section on the mailboxes page with the list of emails in error
- send an email with an unknown sender
- collect the emails
- check that the email appears with an error on the page
=> new: List the emails in error on the mailboxes page

ROADMAP.md
=> doc: Update the roadmap

src/Controller/MailboxesController.php, templates/mailboxes/edit.html.twig, templates/mailboxes/index.html.twig, tests/Controller/MailboxesControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
- add a controller and a template to edit mailboxes
- add a link on the mailboxes page
- go to the mailboxes page
- edit a mailbox
- check that your changes are saved
=> new: Edit mailboxes

src/Controller/MailboxesController.php, src/Controller/PreferencesController.php, src/Controller/ProfileController.php, src/Entity/Mailbox.php, templates/mailboxes/edit.html.twig, templates/mailboxes/index.html.twig, tests/Controller/MailboxesControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
See commits
- check that all test/delete buttons have moved to the mailbox edit page
- with a mailbox in error, update the mailbox → check that the error disappears
- when updating a mailbox → check that a success notification appears
=> imp: Various improvements about mailboxes

src/Command/SeedsCommand.php
N/A
- set coherent datetimes to messages created in seeds
- reset the database → check the messages are in a correct order
=> tec: Fix datetimes of Messages created in seeds

docs/developers/roles.md, src/Controller/PagesController.php, src/Controller/TicketsController.php, src/Repository/AuthorizationRepository.php, src/Repository/OrganizationRepository.php, src/Service/ActorsLister.php
https://github.com/Probesys/bileto/issues/385
- move the code of `getAuthorizedOrganizationIds` from the `AuthorizationRepository` to `OrganizationRepository`
- add the `null` organization logic to the method to return either all the organizations, or only the returned organizations with their sub-organizations
- add documentation
N/A
=> tec: Refactor the code to find the authorized organizations

src/Controller/UsersController.php, tests/Controller/UsersControllerTest.php
N/A
- Redirect to the new user's authorization after its creation
- in the settings, create a user → check that you are invited to add a new authorization
=> imp: Redirect to the user's authorizations after its creation

Makefile, docker/bin/composer, docker/bin/console, docker/bin/npm, docker/bin/php, docker/bin/psql, docs/developers/setup.md
N/A
- change the command `docker-compose` by `docker compose`
- Start the docker dev environment (`make docker-start`) → check it works
- Run the commands under `docker/bin/` → check they work
=> tec: Use Docker Compose v2

docs/administrators/deploy.md
N/A
- change the requirements check by the command `composer check-platform-reqs`
N/A
=> doc: Improve the doc to check requirements in production

docker/bin/psql
https://github.com/Probesys/bileto/pull/392
- rename the `database` service into `psql` in the `docker/bin/psql` script
- run `./docker/bin/psql` → check it opens a psql prompt
=> tec: Fix the psql docker script

.env, env.sample
N/A
- remove most of the comments from the `.env` file
- improve the structure of the `env.sample` file
N/A
=> dev: Reorganize the env files

docs/developers/release.md
=> doc: Document the `dev:` prefix in release document

src/Entity/MetaEntityInterface.php, src/Entity/MetaEntityTrait.php
N/A
- add two methods `isCreatedBy` and `isUpdatedBy` to `MetaEntityInterface`
N/A
=> dev: Add isCreatedBy and isUpdatedBy to the MetaEntityInterface

docs/developers/README.md, docs/developers/email-collector.md, docs/developers/greenmail.md, docs/developers/roles.md, docs/developers/search-engine.md, docs/developers/sorters.md, docs/developers/translations.md
N/A
- move some documents under a new "architecture" section in the developers README
- move the document "Managing the dependencies" under the maintainers section
- change some titles
N/A
=> doc: Reorganize the developers documentation

assets/javascripts/controllers/message_documents_controller.js, templates/message_documents/index.html.twig, templates/tickets/_timeline_message.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/149
- add a button below the editor to upload files
- start a new ticket / answer to a ticket
- upload an archive or text file
- check it's uploaded
- submit the ticket/message
- check the file is attached
=> imp: Allow to upload any kind of files

Makefile, docs/developers/translations.md
N/A
- rename the Make command `i18n-extract` to `translations`
- add documentation about this command
- follow the new documentation → check it works
=> dev: Rename the make i18n-extract command

README.md, ROADMAP.md
=> doc: Update the roadmap and the readme

docs/developers/entity.md
https://github.com/Probesys/bileto/issues/230
- don't ask to reset the database when generating a migration for MariaDB
N/A
=> doc: Improve the doc to generate migrations for MariaDB

templates/bundles/TwigBundle/Exception/error.html.twig, templates/bundles/TwigBundle/Exception/error404.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/384
- provide a generic error page + a custom page for 404 errors
- go to http://localhost:8000/_error/500 and http://localhost:8000/_error/404 → check the pages look good
=> imp: Customize the errors pages

assets/stylesheets/components/messages.css, assets/stylesheets/components/timelines.css
https://github.com/Probesys/bileto/pull/426
See commit
N/A
=> imp: Increase the visibility of messages in the timeline

tests/Command/Users/CreateCommandTest.php, tests/CommandTestsHelper.php, tests/MigrationsTest.php
https://github.com/Probesys/bileto/issues/230
See commits
N/A
=> dev: Improve commands tests

README.md, ROADMAP.md, docs/administrators/README.md, docs/administrators/deploy.md, docs/administrators/update.md, docs/developers/release.md, docs/developers/update.md
=> doc: Adapt the documentation for the "alpha" phase

assets/stylesheets/components/buttons.css, templates/tickets/_search_form.html.twig
N/A
See commits
- go to the tickets list
- check that the buttons are smaller and more discreet
=> imp: Lighten the look of the "quick search" filters

CONTRIBUTING.md
=> doc: Explain how to contribute to the documentation

templates/organizations/show.html.twig, templates/organizations/tickets/new.html.twig, templates/tickets/new.html.twig, templates/tickets/show.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/29
- add a link to the list of tickets in the breadcrumb of tickets and of the new ticket form
- start creating a ticket → check you can click on "Tickets" to come back to the list of tickets
- go to a ticket → check you can click on "Tickets" to come back to the list of tickets
=> imp: Improve breadcrumb to navigate in tickets

translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
=> misc: Fix the order of the translations keys

src/EventSubscriber/EntityActivitySubscriber.php
N/A
- don't create en EntityEvent if changes are empty in postUpdate event
N/A
=> fix: Don't track empty entity changes

assets/stylesheets/components/lists.css, src/Command/SeedsCommand.php
=> fix: Miscellaneous 

.dockerignore, .github/workflows/docker-image.yml, Makefile, docker/production/Dockerfile, docker/production/apache.conf, docker/production/entrypoint.sh
N/A
- provide a Dockerfile for production
- add a Make target to build production images
- configure GitHub Actions to build and push images on ghcr.io
N/A
=> tec: Provide a Docker image for production

assets/stylesheets/components/buttons.css, docs/developers/README.md, docs/developers/buttons.md
N/A
- add a new CSS `.button-group` class
- add documentation about buttons
N/A
=> dev: Add buttons groups

src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php
N/A
- set createdBy of messageDocuments created in the CreateTicketsFromMailboxEmailsHandler
- send an email with an attachment to the support@example.com address
- wait for the scheduler to get and create the ticket
- check there is no error in the logs of the worker
=> fix: Handle email attachments correctly

assets/stylesheets/components/anchors.css, assets/stylesheets/components/buttons.css
N/A
- increase border-radius of buttons and action anchors
- check that buttons and action anchors are rounded
=> imp: Round off the buttons

assets/javascripts/application.js, assets/javascripts/controllers/modal_controller.js, assets/javascripts/controllers/switch_controller.js, assets/javascripts/query_selectors.js, assets/stylesheets/components/forms.css, src/Twig/HoursFormatterExtension.php, tests/Factory/ContractFactory.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
=> dev: Miscellaneous 

migrations/Version20231107141114AddBillingIntervalToContract.php, src/Controller/Organizations/ContractsController.php, src/Controller/Tickets/MessagesController.php, src/Entity/Contract.php, templates/organizations/contracts/new.html.twig, templates/organizations/contracts/show.html.twig, tests/Controller/Organizations/ContractsControllerTest.php, tests/Controller/Tickets/MessagesControllerTest.php, tests/Factory/ContractFactory.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/35
- add a billing interval to the contract entity
- round up the time spent on a ticket, based on the contract's billing interval
- create a contract with a billing interval of 30 minutes
- associate this contract to a ticket
- spend 10 minutes in this ticket
- check that the time charged is 30 minutes (both in the timeline and in the contract)
=> new: Add contract interval billing

src/Repository/TicketRepository.php, src/SearchEngine/QueryBuilder/TicketQueryBuilder.php, templates/organizations/contracts/index.html.twig, tests/SearchEngine/QueryBuilder/TicketQueryBuilderTest.php, tests/SearchEngine/TicketSearcherTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/440
See commits
- go to the list of the contracts of an organization
- check that you see the number of tickets per contract
- click on "x tickets"
- check that you are redirected to the list of the tickets of the contract
=> new: Allow to list the tickets of a contract

.github/pull_request_template.md
=> misc: Remove the Changes section from the PR template

src/Controller/Contracts/MaxHoursController.php, templates/contracts/max_hours/edit.html.twig, templates/organizations/contracts/show.html.twig, tests/Controller/Contracts/MaxHoursControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/441
- create a contract
- click on "extend" and set an additional number of hours for the contract
- check the additional hours are added to the max hours
=> new: Allow to extend the hours in the contracts

docs/developers/release.md
=> doc: Add a process before releasing a version

.vite/vite.config.js, package-lock.json, package.json
=> tec: Upgrade to Vite 5

.phpunit.xml.dist, Makefile, README.md, composer.json, composer.lock, tests/SearchEngine/Query/TokenizerTest.php, tests/Utils/LocalesTest.php
=> tec: Upgrade to PHPUnit 10

assets/stylesheets/application.css, assets/stylesheets/components/pagination.css, docs/developers/README.md, docs/developers/pagination.md, src/Controller/Organizations/TicketsController.php, src/Controller/PagesController.php, src/Controller/TicketsController.php, src/Repository/TicketRepository.php, src/SearchEngine/TicketSearcher.php, src/Utils/Pagination.php, templates/_pagination.html.twig, templates/base.html.twig, templates/organizations/tickets/index.html.twig, templates/pages/home.html.twig, templates/tickets/index.html.twig, tests/SearchEngine/TicketSearcherTest.php, tests/Utils/PaginationTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/383
- create at least 25 tickets
- go to the list of tickets
- check that the tickets are paginated
=> imp: Paginate the list of tickets

src/Command/SeedsCommand.php, templates/organizations/index.html.twig, tests/Command/SeedsCommandTest.php
https://github.com/Probesys/bileto/issues/516
- go to the "organizations" page → check that the link to create sub-organizations doesn't show
=> imp: Deprecate the creation of sub-organizations

migrations/Version20231219162546AlterRemembermeTokenLastUsed.php, migrations/Version20231220083507AlterEntityEventChanges.php
=> misc: Generate missing migrations

src/Entity/Ticket.php, templates/organizations/tickets/new.html.twig, tests/Controller/Organizations/TicketsControllerTest.php
https://github.com/Probesys/bileto/issues/489
1. Go to the "new ticket" form
2. Check that "incident" is selected by default
=> imp: Create "incident" tickets by default

src/Controller/Tickets/MessagesController.php, src/TicketActivity/LifecycleSubscriber.php, src/TicketActivity/MessageDocumentsSubscriber.php, src/TicketActivity/MessageEvent.php, templates/tickets/show.html.twig, tests/Controller/Tickets/MessagesControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/34
- open a ticket
- add an answer with a solution with the assignee → check the status is now "resolved"
- add an answer and refuse the solution with the requester → check the status is now "in progress", and that the solution is removed
- add an answer with a solution with the assignee
- add an answer and approve the solution with the requester → check the status is now "closed"
=> new: Allow to approve or refuse a solution

src/Controller/Organizations/ContractsController.php
https://github.com/Probesys/bileto/issues/501
- create a contract ending with a number and a space, eg. `"Contract 1 "`
- renew the contract → check the contract name is incremented by 1 and doesn't end with a space (eg. `"Contract 2"`)
=> fix: Trim name and notes when creating a contract

assets/stylesheets/components/progress.css
=> imp: Improve the look of the progress bars

.env, .github/workflows/tests.yml, CHANGELOG.md, README.md, docker/development/docker-compose.yml, docs/administrators/deploy.md, env.sample
=> tec: Require PostgreSQL >= 12

src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php
N/A
- send an email to the support address containing invalid HTML (e.g. a tag `<o:p>test</o:p>`)
- collect the emails
- check it doesn't fail
=> fix: Ignore HTML errors when creating tickets from emails

templates/users/authorizations/new.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
N/A
- go to the "new authorization" form
- check the organization form is named "Organizational scope"
=> i18n: Change label of the organization of authorization

docs/developers/roles.md, src/Controller/Organizations/ContractsController.php, src/Controller/Organizations/TicketsController.php, src/Controller/OrganizationsController.php, src/Controller/SettingsController.php, src/Controller/Tickets/MessagesController.php, src/Controller/TicketsController.php, src/Controller/Users/AuthorizationsController.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/SearchEngine/TicketSearcher.php, src/Security/Authorizer.php, src/Service/TicketTimeline.php, src/Twig/SecurityExtension.php
https://github.com/Probesys/bileto/issues/566
N/A
=> dev: Allow to check permissions of any user

Makefile
N/A
- run `make docker-start` and stop it
- run `make docker-clean`
- re-run `make docker-start` and `make db-setup` → check that the system is up
=> dev: Clean all the Docker stuff on make docker-clean

templates/tickets/show.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
#500 
- Be sure to have the prefered language in english
- Select any tickets
- Check if " Ongoing contract" is visible
=> i18n: Change the value of the key tickets.contract

docker/production/Dockerfile
N/A
1. Build the Docker image: `make docker-image VERSION=local`
2. Run the image: `docker run ghcr.io/probesys/bileto:local`
3. Check it says that cache is cleared for "prod" environment (the command fails then but it's normal)
=> tec: Fix installation of dependencies in the Docker image

src/Controller/OrganizationsController.php, src/Entity/Organization.php, src/Form/Type/OrganizationType.php, templates/organizations/_form.html.twig, templates/organizations/new.html.twig, templates/organizations/settings.html.twig, tests/Controller/OrganizationsControllerTest.php
1. Create an organization
2. Edit the organization
3. Check that everything work
=> dev: Refactor the Organization form

docs/developers/roles.md, migrations/Version20240222104331ChangeOperationalRolesToAgent.php, src/Command/SeedsCommand.php, src/Controller/Organizations/TicketsController.php, src/Controller/RolesController.php, src/Controller/Tickets/ActorsController.php, src/Controller/Tickets/FiltersController.php, src/Controller/Users/AuthorizationsController.php, src/Entity/Role.php, src/Repository/AuthorizationRepository.php, src/Repository/OrganizationRepository.php, src/Repository/UserRepository.php, src/Service/ActorsLister.php, templates/organizations/tickets/new.html.twig, templates/roles/_role_form.html.twig, templates/roles/edit.html.twig, templates/roles/index.html.twig, templates/roles/new.html.twig, templates/tickets/actors/edit.html.twig, templates/tickets/filters/edit_actors.html.twig, templates/users/authorizations/index.html.twig, templates/users/authorizations/new.html.twig, tests/AuthorizationHelper.php, tests/Controller/RolesControllerTest.php, tests/Controller/Users/AuthorizationsControllerTest.php, tests/Service/ActorsListerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/576
1. Navigate to the "roles" and "user authorizations" section
2. Check that all reference to "operational roles" have been replaced by "agent roles"
=> imp: Rename "operational" to "agent"

docs/developers/roles.md, src/Command/SeedsCommand.php, src/Controller/Users/AuthorizationsController.php, src/Repository/AuthorizationRepository.php, src/Security/AppVoter.php, tests/Controller/Users/AuthorizationsControllerTest.php, tests/SearchEngine/TicketSearcherTest.php, translations/errors+intl-icu.en_GB.yaml, translations/errors+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/576
1. Create an agent role allowing to access contracts but not managing the organization
1. Create another agent role allowing to manage the organization, but not accessing contracts
2. Grant both roles to your current user in the same organization
3. Check that you can manage the organization AND access its contracts
=> imp: Allow and combine multiple authorizations

docs/developers/roles.md, src/Repository/AuthorizationRepository.php, src/Security/AppVoter.php
https://github.com/Probesys/bileto/pull/588
1. on the `main` branch, go to a simple ticket page (only one message) and check in the Symfony profiler that there are +20 database calls
2. on the `imp/app-voter` branch, go to the same ticket page and check in the Symfony profiler that there are less database calls (~ 10)
=> imp: Improve the AppVoter

assets/javascripts/controllers/form_new_authorization_controller.js, docs/developers/roles.md, migrations/Version20240222153018CreateTeamAuthorization.php, src/Controller/Teams/AgentsController.php, src/Controller/Teams/AuthorizationsController.php, src/Controller/TeamsController.php, src/Controller/Users/AuthorizationsController.php, src/Entity/Authorization.php, src/Entity/Organization.php, src/Entity/Team.php, src/Entity/TeamAuthorization.php, src/Repository/AuthorizationRepository.php, src/Repository/TeamAuthorizationRepository.php, src/Service/Sorter/AuthorizationSorter.php, src/Service/TeamService.php, templates/authorizations/_authorization.html.twig, templates/teams/authorizations/new.html.twig, templates/teams/index.html.twig, templates/teams/show.html.twig, templates/users/authorizations/index.html.twig, tests/Controller/Teams/AgentsControllerTest.php, tests/Controller/Teams/AuthorizationsControllerTest.php, tests/Controller/Users/AuthorizationsControllerTest.php, tests/Factory/TeamAuthorizationFactory.php, translations/errors+intl-icu.en_GB.yaml, translations/errors+intl-icu.fr_FR.yaml, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/576
1. Create a team and add agent in it
2. Create an authorization in the team → check that only "agent" authorizations are suggested
3. Add another agent to the team
4. Go to the authorizations page of each user → check both have an authorization given by the team, and check that you can't revoke it
5. Remove an agent from the team → check the authorization was revoked from this user
6. Revoke the team authorization → check that the other user no longer has this authorization either
=> new: Provide teams authorizations

tests/Controller/MailboxesControllerTest.php, tests/Controller/OrganizationsControllerTest.php, tests/Controller/Teams/AuthorizationsControllerTest.php, tests/FactoriesHelper.php
=> dev: Refactor the clearing of entity manager in tests

.github/workflows/tests.yml, Makefile
N/A
1. open the GitHub actions related to this PR
2. check there is no critical error when running tests against PGSQL DB
3. check the PHPUnit result outputs as TestDox
=> dev: Misc (PHPUnit testdox + db initialization on CI)

.phpunit.xml.dist, composer.json, composer.lock, config/bundles.php, config/packages/doctrine.yaml, symfony.lock, tests/MigrationsTest.php
=> dev: Enable DAMA DoctrineTestBundle in tests

src/Entity/Team.php, src/Entity/TeamAuthorization.php
https://github.com/Probesys/bileto/pull/591
https://github.com/Probesys/bileto/pull/592
- Open Bileto
- Check that the Symfony profiler doesn't complain about invalid entities
=> fix: Fix invalid Team and TeamAuthorization entites

docker/development/php-custom.ini
N/A
- run `make test` → check the script doesn't fail because of memory limit
=> dev: Increase PHP memory in the dev environment

docs/developers/search-engine.md, src/Repository/TicketRepository.php, src/SearchEngine/QueryBuilder/TicketQueryBuilder.php, src/SearchEngine/TicketSearcher.php, tests/SearchEngine/QueryBuilder/TicketQueryBuilderTest.php
N/A
- Search for tickets in the advanced mode: `(contract: #1)`
- Check the form doesn't say there is an error
=> dev: Move TicketRepository methods related to TicketSearcher

docs/developers/roles.md, src/Repository/AuthorizationRepository.php, src/Security/AppVoter.php, src/Security/Authorizer.php, src/Twig/SecurityExtension.php, templates/organizations/tickets/index.html.twig, templates/tickets/index.html.twig, tests/Security/AuthorizerTest.php
N/A
- login with a user with an agent role **without** the "See all the tickets" permission
- check that you can see the tickets views next to the tickets list
=> imp: Display tickets views if user is an agent

tests/AuthorizationHelper.php
=> dev: Provide AuthorizationHelper::grantTeam

src/Controller/TeamsController.php, tests/Controller/TeamsControllerTest.php
https://github.com/Probesys/bileto/issues/576
1. create a team
2. check that you're redirected to it
=> imp: Redirect to team after its creation

templates/contracts/show.html.twig, templates/mailboxes/edit.html.twig, templates/organizations/settings.html.twig, templates/roles/edit.html.twig, templates/teams/edit.html.twig, templates/teams/show.html.twig, templates/tickets/show.html.twig, templates/users/authorizations/index.html.twig, templates/users/edit.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
=> dev: Extract common translations keys

src/Controller/RolesController.php, src/Entity/Role.php, tests/AuthorizationHelper.php
https://github.com/Probesys/bileto/issues/560
N/A
=> dev: Sanitize roles permissions in the setter

migrations/Version20240425135404SetContractUpdatedByNullable.php, src/Entity/Contract.php
https://github.com/Probesys/bileto/issues/560
N/A
=> dev: Allow contract.updatedBy to be null

docs/developers/README.md, docs/developers/import-data.md, src/Command/Data/ImportCommand.php, src/Entity/Contract.php, src/Entity/Ticket.php, src/Entity/User.php, src/Service/DataImporter/DataImporter.php, src/Service/DataImporter/DataImporterError.php, src/Service/DataImporter/Index.php, src/Service/DataImporter/IndexError.php, tests/Service/DataImporter/DataImporterTest.php
https://github.com/Probesys/bileto/issues/560
- reset the data with `make db-reset FORCE=true`
- create an archive matching the spec (sorry, too long to provide a working archive)
- run the command `./docker/bin/console app:data:import /path/to/archive.zip`
- login and check that data are present
=> new: Allow to import data from a ZIP archive

src/Service/Sorter/LocaleSorter.php
https://github.com/Probesys/bileto/issues/558
N/A
=> misc: Remove the typehint on Collator::compare

assets/stylesheets/components/timelines.css, templates/pages/home.html.twig
https://github.com/Probesys/bileto/issues/562
- assign at least 6 tickets to yourself
- go to home page → check the "see all your tickets" link looks nice
=> imp: Improve "See all tickets" link on the home page

assets/stylesheets/custom/tickets-show.css, src/Controller/Tickets/MessagesController.php, src/Controller/TicketsController.php, templates/tickets/show.html.twig, tests/Controller/Tickets/MessagesControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/562
- create a ticket with an agent who can post confidential messages
- assign the ticket to yourself
- check the answer form have a new select box to choose the type of the answer
- choose "Confidential answer" and post the answer → check the message is confidential
- do the same with "Solution"
- refuse the solution → check the solution is removed
- repost a solution, and approve it → check the ticket is closed
=> imp: Rework the answer form

templates/organizations/tickets/new.html.twig
https://github.com/Probesys/bileto/issues/562
- go to the form to create a ticket
- check the actors and priority are put in accordions
- check the actors accordion is open by default
=> imp: Use accordions in the new ticket form

assets/javascripts/controllers/checkboxes_controller.js, src/SearchEngine/TicketFilter.php, templates/roles/_role_form.html.twig, templates/tickets/_search_form.html.twig, tests/SearchEngine/TicketFilterTest.php
https://github.com/Probesys/bileto/issues/562
- go to the list of tickets
- verify that "open" status filter is checked as well as its sub-checkboxes
- uncheck one of the sub-checkbox → verify that "open" is unchecked
- check "open" → verify that all the sub-checkboxes are checked again
- uncheck "open" → verify that all the sub-checkboxes are unchecked
- check "open" and submit the form → verify in the "advanced search" that only "open" status is selected
=> imp: Improve the behaviour of checkboxes in filters

assets/stylesheets/components/forms.css
https://github.com/Probesys/bileto/pull/628
- go to a ticket as an assignee
- select "Confidential answer" → verify that the text doesn't cover the icon
=> fix: Fix the look of "small" select icon

assets/javascripts/controllers/tinymce_controller.js
https://github.com/Probesys/bileto/pull/625
- go to the "new ticket" page
- open the console and refresh the page
- verify there is no warning about the license of TinyMCE
=> fix: Activate TinyMCE with "gpl" license

assets/javascripts/controllers/navigation_controller.js
N/A
- with Firefox ESR (115), open Bileto with the mobile view (ctrl + maj + m)
- verify that the button to open/close the main menu works
=> fix: Fix the main navigation button on Firefox ESR mobile

translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
=> fix: Fix i18n mistakes

src/Controller/Organizations/ContractsController.php, src/Form/Type/ContractType.php, src/Repository/TicketRepository.php, templates/contracts/_form.html.twig, templates/contracts/edit.html.twig, templates/organizations/contracts/new.html.twig, templates/tickets/contracts/edit.html.twig, tests/Controller/Organizations/ContractsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/610
1. Create a ticket with no contracts
2. Add some spent time
3. In the same organization, create a contract and check both "Associate existing tickets created during the contract period" and "Associate existing unaccounted spent times" checkboxes
4. Verify that the ticket is attached to the contract and that the spent time is now accounted
=> Allow to assign tickets and unaccounted times on contract (re)newal

src/Command/SeedsCommand.php
N/A
- run `make db-reset FORCE=true`
- login with `alix@example.com / secret`
- verify in Admin > Roles > Technicians that all the permissions are checked
=> dev: Give all agent permissions to techs in dev environment

src/Entity/Ticket.php
=> dev: Fix Doctrine deprecation warning about ordering

assets/stylesheets/components/popups.css, templates/tickets/_sort_button.html.twig
https://github.com/Probesys/bileto/issues/651
1. open the application on mobile
2. open the user menu
3. verify that the menu appears next to the "My account" button instead of the bottom of the screen
=> imp: Improve the popup menu on mobile

assets/stylesheets/components/placeholders.css, templates/contracts/index.html.twig, templates/organizations/contracts/index.html.twig, templates/teams/index.html.twig, templates/teams/show.html.twig
N/A
- open the contracts indexes, teams index and team page
- verify there is no data and that an illustration is used as a placeholder
=> imp: Use an illustration on all placeholders

migrations/Version20240619125014SetDeleteCascadeOnContractAndTimeSpent.php, src/Controller/OrganizationsController.php, src/Entity/Contract.php, src/Entity/TimeSpent.php, tests/Controller/OrganizationsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
N/A
- create an organization
- create an ongoing contract in this orga
- attach a ticket to this contract, and add spent time
- set your current user's organization to the organization
- delete the organization → verify that it works
=> fix: Fix deletion of organizations

docker/development/ldap-ldifs/tree.ldif, docs/developers/setup.md, src/Command/SeedsCommand.php, src/Command/Users/CreateCommand.php, src/Controller/Teams/AgentsController.php, src/Controller/UsersController.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/MessageHandler/SynchronizeLdapHandler.php, src/Security/FormLoginAuthenticator.php, src/Service/Ldap.php, src/Service/UserCreator.php, src/Service/UserCreatorException.php, tests/MessageHandler/SynchronizeLdapHandlerTest.php, tests/Service/UserCreatorTest.php
https://github.com/Probesys/bileto/issues/646
1. reset the data (`make db-reset FORCE=true`)
2. verify the organizations handle domains
3. verify that "Friendly Coorp" is now named "Friendly Coop"
4. try to create a user → verify it still works
=> dev: Miscelleanous

templates/organizations/tickets/index.html.twig, templates/tickets/_search_form.html.twig, templates/tickets/index.html.twig
N/A
1. login with a simple user
2. go to the list of tickets
3. verify the "actors" filters aren't shown
=> imp: Hide actors filter to simple users

tests/Factory/AuthorizationFactory.php, tests/Factory/ContractFactory.php, tests/Factory/MailboxFactory.php, tests/Factory/MessageDocumentFactory.php, tests/Factory/MessageFactory.php, tests/Factory/OrganizationFactory.php, tests/Factory/RoleFactory.php, tests/Factory/TeamAuthorizationFactory.php, tests/Factory/TicketFactory.php, tests/Factory/TimeSpentFactory.php, tests/Factory/UserFactory.php
=> dev: Remove uid from the entities factories

src/Controller/UsersController.php, src/Repository/AuthorizationRepository.php, src/Repository/ContractRepository.php, src/Repository/OrganizationRepository.php, src/Repository/UserRepository.php
=> tec: Improve performance when fetching from the database

migrations/Version20240704073844RemovePostgreSQLSequences.php
https://github.com/Probesys/bileto/pull/667
- make sure to use PostgreSQL
- apply the migration
- answer to a ticket
- verify it works (before this patch, it would fail)
=> tec: Remove the old PostgreSQL sequences

.phpunit.xml.dist, config/packages/doctrine.yaml, src/Controller/Contracts/AlertsController.php, src/Controller/ContractsController.php, src/Controller/MailboxEmailsController.php, src/Controller/MailboxesController.php, src/Controller/MessageDocumentsController.php, src/Controller/Organizations/ContractsController.php, src/Controller/Organizations/TicketsController.php, src/Controller/Organizations/UsersController.php, src/Controller/OrganizationsController.php, src/Controller/RolesController.php, src/Controller/Teams/AgentsController.php, src/Controller/Teams/AuthorizationsController.php, src/Controller/TeamsController.php, src/Controller/Tickets/ActorsController.php, src/Controller/Tickets/ContractsController.php, src/Controller/Tickets/MessagesController.php, src/Controller/Tickets/PriorityController.php, src/Controller/Tickets/StatusController.php, src/Controller/Tickets/TitleController.php, src/Controller/Tickets/TypeController.php, src/Controller/TicketsController.php, src/Controller/Users/AuthorizationsController.php, src/Controller/UsersController.php
N/A
- Go to a ticket page for instance
- Verify there is no deprecation warning in the Symfony dev bar
=> dev: Make Doctrine entities mapping explicit

src/Controller/TicketsController.php, src/Repository/TicketRepository.php
https://github.com/Probesys/bileto/pull/670
N/A
=> imp: Improve performance when showing a ticket

src/Controller/UsersController.php, tests/Controller/UsersControllerTest.php
https://github.com/Probesys/bileto/issues/582
https://github.com/Probesys/bileto/issues/646
- In the admin, create a user
- Verify you're redirected to the user page
=> imp: Redirect to user page after creation

src/Controller/RolesController.php, src/Entity/Organization.php, src/Entity/Role.php, src/Form/Type/RoleType.php, templates/roles/_form.html.twig, templates/roles/edit.html.twig, templates/roles/new.html.twig, tests/Controller/RolesControllerTest.php
- in the admin, create a new role
- verify it works and the role is created
- edit the role (e.g. change the permissions)
- verify your changes are saved
=> dev: Refactor the role form with Symfony Form

composer.lock
https://github.com/Probesys/bileto/issues/674
N/A
=> dev: Update to Foundry 2.0.6

src/SearchEngine/QueryBuilder/TicketQueryBuilder.php, tests/SearchEngine/QueryBuilder/TicketQueryBuilderTest.php, tests/SearchEngine/TicketSearcherTest.php
N/A
1. Create an ongoing contract
2. Attach a ticket to this contract and make sure another ticket has no contracts
3. In the advanced search, search for `has:contract`
4. Verify that it shows the ticket with the contract
3. In the advanced search, search for `no:contract`
4. Verify that it shows the ticket without contracts
5. Go to the list of contracts and click to open the list of tickets of the contract
6. Verify that it shows the ticket with the contract
7. Search for `NOT contract:#X` (where `X` is the id of the contract)
4. Verify that it shows the ticket without the contract
=> imp: Search tickets with(out) contracts

assets/stylesheets/components/forms.css, assets/stylesheets/utils/flow.css, templates/profile/edit.html.twig, templates/roles/_form.html.twig, templates/tickets/_list.html.twig, templates/tickets/_search_form.html.twig, templates/tickets/show.html.twig
=> imp: Miscellaneous improvements

src/Entity/Ticket.php
https://github.com/Probesys/bileto/issues/283
https://github.com/Probesys/bileto/pull/682
1. Create several labels
2. Attach them all to a ticket
3. Verify that the labels are correctly sorted on the ticket page and in the tickets list
=> imp: Order tickets' labels by name

src/SearchEngine/QueryBuilder/TicketQueryBuilder.php, tests/SearchEngine/QueryBuilder/TicketQueryBuilderTest.php, tests/SearchEngine/TicketSearcherTest.php
N/A
1. Create a team and add your user in the team
2. Create 4 tickets: one assigned to your user, one assigned to another user, one assigned to your team only, and one not assigned (requester must be someone else each time)
3. Filter the list of tickets with `involves:@me`
4. Verify that you see the ticket assigned to yourself and the one assigned to your team
3. Filter the list of tickets with `NOT involves:@me`
4. Verify that you see the unassigned ticket and the one assigned to the other user
=> fix: Fix search with "NOT involves" not returning correct results

docs/developers/import-data.md, src/Service/DataImporter/DataImporter.php, tests/Service/DataImporter/DataImporterTest.php
=> imp: Allow to import the organizations' domains

src/Controller/UsersController.php, tests/Controller/UsersControllerTest.php
N/A
1. Go to the users list and click on a user
2. Update the user
3. Verify that you're redirected to the user page instead of the users list
=> fix: Redirect to the user page after updating

docs/developers/import-data.md, src/Service/DataImporter/DataImporter.php, tests/Service/DataImporter/DataImporterTest.php
https://github.com/Probesys/bileto/issues/39
1. Create a ZIP archive to import, containing a ticket having an observer
2. Import the archive (`./docker/bin/console app:data:import data.zip`)
3. Verify that the ticket is imported with the correct user as an observer
=> imp: Allow to import tickets' observers

src/Command/Users/CreateCommand.php, tests/Command/Users/CreateCommandTest.php
https://github.com/Probesys/bileto/issues/530
1. Create a user with the CLI and pass the `--locale` option (make sure to pass the value different from the default one): `./docker/bin/console app:user:create --locale=fr_FR --email=dominique@example.com --password=secret`
2. Login with the user
3. Verify that the user has the correct locale set
=> imp: Allow to pass locale when creating user with CLI

templates/base.html.twig
N/A
1. on mobile, go to the reset password form
2. verify that the header looks good
=> fix: Fix the header on mobile when not connected

docs/developers/create-user.md, src/Controller/Tickets/TitleController.php, src/Entity/User.php, src/Form/Ticket/TitleForm.php, src/MessageHandler/SynchronizeLdapHandler.php, src/Security/FormLoginAuthenticator.php, src/Service/DataImporter/DataImporter.php, src/Service/UserCreator.php, templates/tickets/title/edit.html.twig, tests/Controller/Tickets/TitleControllerTest.php, tests/Factory/UserFactory.php, tests/Service/DataImporter/DataImporterTest.php
=> dev: Miscellaneous refactorings

docs/developers/roles.md, src/Controller/MessageDocumentsController.php, src/Controller/Tickets/ActorsController.php, src/Controller/Tickets/ContractsController.php, src/Controller/Tickets/LabelsController.php, src/Controller/Tickets/MessagesController.php, src/Controller/Tickets/PriorityController.php, src/Controller/Tickets/StatusController.php, src/Controller/Tickets/TitleController.php, src/Controller/Tickets/TypeController.php, src/Controller/TicketsController.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/Security/AppVoter.php, tests/Controller/TicketsControllerTest.php
=> sec: Allow to check permissions on tickets with the AppVoter

src/Controller/BaseController.php, src/Controller/Tickets/ActorsController.php, src/Controller/Tickets/ContractsController.php, src/Controller/Tickets/LabelsController.php, src/Controller/Tickets/MessagesController.php, src/Controller/Tickets/PriorityController.php, src/Controller/Tickets/StatusController.php, src/Controller/Tickets/TitleController.php, src/Controller/Tickets/TypeController.php, src/Entity/Ticket.php, templates/tickets/show.html.twig, tests/Controller/Tickets/ActorsControllerTest.php, tests/Controller/Tickets/ContractsControllerTest.php, tests/Controller/Tickets/LabelsControllerTest.php, tests/Controller/Tickets/MessagesControllerTest.php, tests/Controller/Tickets/PriorityControllerTest.php, tests/Controller/Tickets/StatusControllerTest.php, tests/Controller/Tickets/TitleControllerTest.php, tests/Controller/Tickets/TypeControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/275
1. Close a ticket
2. Verify that all the actions are disabled / not available except reopening the ticket
3. Reopen the ticket
4. Verify the ticket is reopened
=> imp: Forbid actions in closed tickets

assets/stylesheets/components/timelines.css, templates/tickets/show.html.twig
=> imp: Various improvements to timeline dates

migrations/Version20240828075802AddStatusChangedAtToTicket.php, src/Entity/Ticket.php, src/Message/ProcessPreviouslyResolvedTickets.php, src/MessageHandler/ProcessPreviouslyResolvedTicketsHandler.php, src/Repository/TicketRepository.php, src/Scheduler/DefaultScheduleProvider.php, src/TicketActivity/LifecycleSubscriber.php, src/TicketActivity/TicketEvent.php, src/Twig/TicketEventChangesFormatterExtension.php, templates/tickets/_timeline_event.html.twig, tests/MessageHandler/ProcessPreviouslyResolvedTicketsHandlerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/561
1. Resolve a ticket
2. Wait for one week 👀
3. Verify that the system user closed the ticket
=> new: Autoclose resolved tickets after 7 days

src/ActivityMonitor/RecordableEntitiesSubscriber.php, src/Controller/Organizations/TicketsController.php, src/Entity/Ticket.php, src/Form/Ticket/ActorsForm.php, src/Form/Ticket/LabelsForm.php, src/Service/DataImporter/DataImporter.php, tests/ActivityMonitor/RecordableEntitiesSubscriberTest.php
https://github.com/Probesys/bileto/pull/720/commits/a20a96e50441744614579c4cb9d4d8dbffd23937
1. Add observer(s) and label(s) to a ticket
2. Verify it appears in the ticket's timeline
1. Remove all the observers and labels from the ticket
2. Verify it appears in the ticket's timeline
=> dev: Record emptying ticket's observers and labels

src/Controller/Tickets/MessagesController.php, src/Message/SendReceiptEmail.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/MessageHandler/SendReceiptEmailHandler.php, src/TicketActivity/NotificationsSubscriber.php, templates/emails/receipt.html.twig, tests/Controller/Organizations/TicketsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/296
1. Configure an email client for a user (https://github.com/Probesys/bileto/blob/main/docs/developers/greenmail.md#with-thunderbird-or-any-external-mail-client)
2. Create a ticket with this user as requester
3. Verify that you receive a receipt for the request
=> new: Send a receipt to requester when ticket is opened

src/Entity/Ticket.php, src/MessageHandler/SendMessageEmailHandler.php, tests/Controller/Tickets/MessagesControllerTest.php
N/A
1. Create a ticket and assign it
2. In an email client, send answers to the ticket between the requester and the assignee
3. Verify that emails are threaded
=> imp: Allow to thread followup emails in clients

docs/developers/import-data.md, src/Service/DataImporter/DataImporter.php, tests/Service/DataImporter/DataImporterTest.php
=> tec: Allow to import ticket.updatedAt

src/Service/DataImporter/DataImporter.php
=> tec: Validate only new entities during importation

docs/developers/import-data.md, src/Service/DataImporter/DataImporter.php, tests/Service/DataImporter/DataImporterTest.php
https://github.com/Probesys/bileto/issues/727
- create an archive to import, including a ticket message with an `emailId` field (can be any string less than 1000 chars)
- import the archive
- verify that it's imported in the database
=> tec: Allow to import Messages emailId

src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
https://github.com/Probesys/bileto/issues/727
- in GLPI, create a ticket and get the notification email
- export and import the GLPI data
- configure a mailbox
- answer to the notification email by making sure to send it to the mailbox' email
- verify that it's associated to the ticket imported from GLPI
=> imp: Detect emails answering to a GLPI server

composer.json, composer.lock, config/bundles.php, config/packages/monolog.yaml, config/packages/sentry.yaml, config/services.yaml, docs/administrators/deploy.md, env.sample, src/Controller/PagesController.php, symfony.lock, tests/ActivityMonitor/RecordableEntitiesSubscriberTest.php
=> tec: Allow to send errors to a Sentry server

src/TicketActivity/OngoingContractSubscriber.php, tests/Controller/Tickets/OrganizationControllerTest.php
https://github.com/Probesys/bileto/issues/729
1. Create two ongoing contracts in two different organizations
2. Create a ticket in one of the organization and associate a contract and (accounted) spent time
3. Transfer the ticket to the other organization
4. Verify that the spent time is accounted for the contract of the new organization
=> imp: Account time spent on new contract during a transfer

docs/developers/import-data.md, src/Service/DataImporter/DataImporter.php, src/Service/DataImporter/Index.php, tests/Service/DataImporter/DataImporterTest.php
N/A
- Create an archive with a "isDefault" role
- Import the archive
- Verify that the role is imported as the default one
=> tec: Allow to import the default role

src/Repository/ContractRepository.php
N/A
1. Import a lot of data (contracts with tickets and spent time)
2. Go to the list of contracts
3. Verify the pagination is correct
=> fix: Fix contracts pagination

assets/stylesheets/components/messages.css
N/A
1. open a ticket, the message must be a single (very) long word (no space, no dash, just chars)
2. verify that the message don't expand out of the screen once posted
=> fix: Make sure messages don't expand out of the screen

src/Command/Data/ImportCommand.php, src/Service/DataImporter/DataImporter.php, src/Service/MessageDocumentStorage.php, tests/Controller/MessageDocumentsControllerTest.php, tests/MessageDocumentStorageHelper.php, tests/Service/DataImporter/DataImporterTest.php
N/A
1. Create an archive containing a ticket with a SVG document
2. Import the data without passing the `--trust-mimetypes` argument
3. Verify the command fails
4. Reset the database and import the data with passing `--trust-mimetypes` argument
5. Verify the command works
=> tec: Improve the importation of documents

src/Form/Type/ActorType.php, src/Form/Type/TeamType.php, templates/organizations/_form.html.twig
=> fix: "optional" label and declaration of allowed types in forms

Makefile, docs/developers/update.md
=> dev: Provide a command to pull the Docker images

templates/organization.html.twig
=> a11y: Add missing labels to buttons in organization template

src/Controller/Organizations/TicketsController.php, src/Service/TicketAssigner.php, src/Utils/ArrayHelper.php, tests/Controller/Organizations/TicketsControllerTest.php
https://github.com/Probesys/bileto/issues/647
1. create a responsible team and grant it an authorization on an organization
2. with a simple user who cannot change the actors, create a ticket with the interface in this organization
3. verify that the ticket is assigned to the team
=> fix: Various fixes about assignment of responsible teams

src/Controller/RolesController.php, src/Repository/RoleRepository.php
=> fix: Unset correctly previous default role when changing

src/Form/UserForm.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/747
1. Create a user with an access to at least one organization
2. Edit him
3. Verify that the placeholder of the organization is "Automatic" instead of "No organization"
=> imp: Change label of the placeholder of user form organization

docs/administrators/README.md, docs/administrators/import-data.md
=> doc: Explain to admins how to import data

assets/stylesheets/components/enclosures.css, src/Controller/Organizations/TicketsController.php, src/Controller/Tickets/MessagesController.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/TicketActivity/DefaultObserversSubscriber.php, src/TicketActivity/LifecycleSubscriber.php, src/TicketActivity/MessageDocumentsSubscriber.php, src/TicketActivity/MessageEvent.php, src/TicketActivity/NotificationsSubscriber.php, templates/form/bileto_theme.html.twig
=> dev: Miscellaneous refactoring around forms

assets/javascripts/controllers/form_new_authorization_controller.js, src/Controller/Teams/AuthorizationsController.php, src/Controller/Users/AuthorizationsController.php, src/Entity/Role.php, src/Form/Team/AuthorizationForm.php, src/Form/Type/RoleType.php, src/Form/User/AuthorizationForm.php, src/Service/TeamService.php, templates/teams/authorizations/new.html.twig, templates/users/authorizations/new.html.twig, tests/AuthorizationHelper.php, tests/Controller/Teams/AuthorizationsControllerTest.php, tests/Controller/Users/AuthorizationsControllerTest.php, translations/errors+intl-icu.en_GB.yaml, translations/errors+intl-icu.fr_FR.yaml
1. test the authorization forms (user and team)
2. verify everything works as expected
=> dev: Refactor the authorization forms

src/Form/Ticket/AdvancedSearchForm.php, src/Form/Ticket/QuickSearchForm.php, src/SearchEngine/Ticket/QuickSearchFilterBuilder.php, templates/organizations/tickets/index.html.twig, templates/tickets/_search_form.html.twig, templates/tickets/index.html.twig, tests/SearchEngine/Ticket/QuickSearchFilterBuilderTest.php
=> fix: Miscellaneous fixes about tickets search

templates/tickets/actors/edit.html.twig, templates/tickets/show.html.twig
N/A
2. Verify that the observers are listed after the assignee
3. Edit the actors, verify that the observers field is shown at the end of the form
=> imp: Move the observers after the assignee

docker/production/Dockerfile
https://github.com/Probesys/bileto/pull/787
1. run `make docker-image VERSION=dev`
2. verify it works
=> tec: Fix the building of the Docker image

config/packages/sentry.yaml
https://github.com/Probesys/bileto/pull/740
1. Run Bileto in prod environment
2. Verify it works (e.g. you can access the login form)
=> tec: Make Sentry optional in production

docs/administrators/README.md, docs/administrators/backup.md
=> doc: Add documentation about backup and restore in production

CONTRIBUTING.md, README.md, docker/production/Dockerfile, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
=> misc: Change Probesys website URL by probesys.coop

docker/bin/mariadb, docs/developers/setup.md
N/A
1. Start Bileto with MariaDB `make docker-start DATABASE=mariadb`
2. Run `./docker/bin/mariadb bileto`
3. Verify that it works
=> dev: Provide a command to run mysql command in Docker container

Makefile, docker/development/docker-compose.yml, docs/developers/setup.md, docs/developers/tests.md
N/A
1. run `make docker-start PORT=9000` → verify that the application runs on port 9000
2. run `make install INSTALLER=npm` → verify that it installs only the NPM packages
3. run `make db-migrate VERSION=prev` → verify it rollbacks the latest migration
4. run `make lint LINTER=phpstan` → verify that it runs only PHPStan (do the same with the other linters)
=> dev: Improve the Makefile

.github/workflows/tests.yml
=> dev: Fix the DB configuration on the CI

.github/workflows/tests.yml, composer.json, composer.lock, config/packages/lock.yaml, migrations/Version20241119153023CreateLockKeys.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/MessageHandler/FetchMailboxesHandler.php, symfony.lock
https://github.com/Probesys/bileto/issues/772
1. Make sure to restart the worker
1. Send an email to `support@example.com`
2. Wait for the worker to process the email and verify a ticket is created
3. Send an email to `support@example.com`
4. Click on "Collect mailboxes" in the admin and verify a ticket is created
5. Verify in the database that all the locks have been released: `./docker/bin/psql bileto -c "SELECT * FROM lock_keys;"`
=> tec: Lock mailbox collection and mailbox emails processing

src/MessageHandler/SynchronizeLdapHandler.php
https://github.com/Probesys/bileto/issues/783
- remove the email of dominique user in `docker/development/ldap-ldifs/tree.ldif`
- reset the Docker data: `make docker-clean` and `make db-setup`
- sync the LDAP data `./docker/bin/console app:ldap:sync`
- verify that the error is logged as a warning and not as an error
=> tec: Log only warning if a user cannot be created with LDAP

docs/developers/import-data.md, migrations/Version20241120104651AddNotificationsReferencesToMessage.php, migrations/Version20241120143635DropMessageEmailId.php, src/Entity/Message.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/MessageHandler/SendMessageEmailHandler.php, src/MessageHandler/SendReceiptEmailHandler.php, src/Repository/MessageRepository.php, src/Service/DataImporter/DataImporter.php, tests/Controller/Organizations/TicketsControllerTest.php, tests/Controller/Tickets/MessagesControllerTest.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php, tests/Service/DataImporter/DataImporterTest.php
https://github.com/Probesys/bileto/issues/797
1. Create a ticket with a user
2. You must receive a receipt email 
3. Answer to this email
4. Collect the emails
5. Verify that the answer is added to the initial ticket
=> imp: Allow to answer to the receipt emails

src/Repository/ContractRepository.php, tests/Controller/ContractsControllerTest.php
N/A
1. Create several contracts with different name and different end dates
2. Verify that the contracts are ordered uniquely by names in the global list of contracts
=> imp: Order contracts by name in the global list

translations/messages+intl-icu.fr_FR.yaml
N/A
1. Create a request
2. Make sure the interface is in French
3. In the list of tickets, verify that the ticket is indicated as "Demande ouverte le..."
=> fix: Use "demande" instead of "requête" in French translation

README.md, ROADMAP.md
=> doc: Update the available features and the roadmap

.phpstan.neon, composer.json, composer.lock, src/Controller/BaseController.php
=> dev: Install and configure phpstan-symfony

src/Entity/Contract.php, src/Repository/ContractRepository.php
N/A
- create an ongoing contract
- spend time on it until it's completely consumed
- verify its status is still "in progress"
=> imp: Don't consider consumed contracts as finished

tests/MessageHandler/SynchronizeLdapHandlerTest.php
=> misc: Fix a Ldap test failing randomly

assets/stylesheets/custom/tickets.css, src/Controller/Tickets/MessagesController.php, src/Form/AnswerForm.php, src/Misc/AdditionalTranslations.php, src/TicketActivity/LifecycleSubscriber.php, templates/form/bileto_theme.html.twig, templates/tickets/show.html.twig, tests/Controller/Tickets/MessagesControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/820
1. Add a solution to a ticket
2. As assignee, verify that you can approve / refuse the solution or simply answer with no decision
3. As requester, verify that you can just approve / refuse the solution
=> imp: Rework solution approvement to allow agents to approve or refuse

assets/stylesheets/components/popups.css
N/A
1. Open the contracts' sort popup
2. Verify the text doesn't overflow
=> fix: Fix overflowing centered popup containers

src/Entity/MessageDocument.php
N/A
- download an email as an .eml file
- try to upload the file as attachment of a message
- verify that it works
=> imp: Accept .eml files as attachments

src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/MessageHandler/SendMessageEmailHandler.php, src/Utils/DomHelper.php, tests/Utils/DomHelperTest.php
https://github.com/Probesys/bileto/issues/782
1. Create a ticket with an assignee different from the requester
2. Add an answer and insert an image in the body
3. Verify that the image appears correctly in the email sent by Bileto
4. Answer to the email by keeping the image in the body
5. Verify that the image still appears in Bileto
6. Verify that the image also appears in the email sent to the other user
=> fix: Display the images in notification emails correctly

src/Form/AnswerForm.php, templates/tickets/show.html.twig
https://github.com/Probesys/bileto/issues/836
1. add an answer without specifying time
2. verify the answer is added and no time spent is added
3. click on the "Time spent" button and type "5"
2. verify the answer is added and that 5 minutes are spent
3. click on the "Time spent" button but leave the input empty
2. verify the answer is added and no time spent is added
=> imp: Improve the UX of the "time spent" input

assets/stylesheets/components/forms.css
https://github.com/Probesys/bileto/issues/838
1. go to pages with radio buttons or checkboxes
2. verify they look great
=> fix: Fix the checkbox and radio buttons glitch aspect

src/MessageHandler/SendMessageEmailHandler.php
https://github.com/Probesys/bileto/issues/843
2. Add a solution
3. Verify that the sent email contains "[Resolved]" in the subject
4. Accept the solution
3. Verify that the sent email contains "[Closed]" in the subject
=> imp: Add the status to the message emails subject if finished

src/Controller/Organizations/TicketsController.php, src/Controller/PagesController.php, src/Controller/TicketsController.php, src/SearchEngine/Ticket/Searcher.php, templates/organization.html.twig, templates/organizations/tickets/index.html.twig, templates/pages/home.html.twig, templates/tickets/_menu.html.twig, templates/tickets/index.html.twig, tests/Controller/Organizations/TicketsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/832
1. Create several tickets (more than 5) where requester and assignee are different. The requester must not be an agent.
2. Also create tickets assigned to a team which includes the assignee
3. Verify on the home page:
- that the tickets appears when logged in as the requester
- that the tickets appears when logged in as the assignee (except those assigned to the team)
4. Verify that when clicking on "See all your tickets", you're redirected to the "Your tickets" view as the requester, or to the new "Your assigned tickets" as the assignee.
=> imp: Display assigned tickets on home page if user is agent

src/Entity/Ticket.php, templates/tickets/_list.html.twig, templates/tickets/show.html.twig, tests/Entity/TicketTest.php, tests/Factory/TimeSpentFactory.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/499
1. Create a ticket without contract
2. Add spent time on it
3. Add a contract on it (with a time accounting unit), but don't associate the unaccounted time on it
4. Add spent time on it
With both permissions to see real and accounted time, verify that you can see:
- the total real, accounted and unaccounted time in the left column of the ticket
- the total accounted and unaccounted time in the tickets lists
With only the permission to see real time, verify that you can see:
- the total real time in the left column of the ticket
- the total real time in the tickets lists
With only the permission to see accounted time, verify that you can see:
- the total accounted time in the left column of the ticket
- the total accounted time in the tickets …
=> imp: Display the total time spent in the tickets and their lists

.gitignore, config/packages/twig.yaml, config/services.yaml, src/Twig/SettingsExtension.php, templates/emails/transactional.html.twig
https://github.com/Probesys/bileto/issues/842
1. Create a ticket 
2. Verify that the receipt email shows the Bileto logo
3. Put a SVG file named `logo.svg` under the `var/settings/` folder
4. Create a ticket
5. Verify that the receipt email shows the new logo
=> imp: Allow to customize the logo in the emails

docker/production/Dockerfile, docker/production/entrypoint.sh
=> tec: Make sure folders under var are created in Docker image

docs/administrators/docker.md
=> doc: Document database volume mounting in the Docker config for admins

src/Controller/ContractsController.php, src/Form/Organization/SelectForm.php, templates/contracts/index.html.twig, templates/contracts/new.html.twig, tests/Controller/ContractsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/850
1. Go to the "contracts" page
2. Click on "New contract"
3. Select an organization
4. Verify that you're redirected to the selected organization's contracts page
=> Allow to create a contract from the global list of contracts

assets/stylesheets/components/buttons.css, docs/developers/buttons.md, src/Controller/TimeSpentsController.php, src/Entity/TimeSpent.php, src/Form/TimeSpentForm.php, src/Service/ContractTimeAccounting.php, templates/tickets/_time_spent.html.twig, templates/tickets/_timeline_time_spent.html.twig, templates/time_spents/edit.html.twig, tests/Controller/TimeSpentsControllerTest.php, tests/Service/ContractTimeAccountingTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/445
1. Create a ticket with a contract (time accounting unit of 10)
2. Add spent time on the ticket (real time = 5)
3. Verify that the accounted time is 10
4. Edit the spent time (real time = 15)
3. Verify that the real time is now 15 and the accounted time is 20
=> imp: Allow to update the spent times

src/Repository/MessageRepository.php
=> fix: Fix getting message reference if duplicated

src/Utils/DomHelper.php
=> fix: Make sure to return valid UTF8 string in DomHelper

src/MessageHandler/SendMessageEmailHandler.php, src/MessageHandler/SendReceiptEmailHandler.php
=> fix: Catch errors if cannot save message notification reference

migrations/Version20250107141916ChangeTicketSolutionOnDeleteSetNull.php, src/Entity/Ticket.php
N/A
1. Create a ticket with a solution
2. Try to delete the ticket in the database (`DELETE FROM ticket WHERE id = ...`)
3. Verify the ticket is deleted
=> tec: Allow to delete tickets with solution

docs/developers/import-data.md
=> doc: Add a note about datetimes offset to the doc of data importation

migrations/Version20250108144931ChangeMessageDocumentMessageOnDeleteCascade.php, src/Entity/MessageDocument.php
=> tec: Allow to delete messages with documents

src/Repository/AuthorizationRepository.php
https://github.com/Probesys/bileto/issues/899
1. Make sure that the "user" role cannot see all the tickets
2. Restart the worker if needed
3. Create a ticket with a user
4. Try to answer to the receipt email with another user and let the worker collect the email (this is important to not do it manually!)
5. Verify it creates a new ticket instead of answering to the initial ticket
6. Change the "user" role to add the permission "See all the tickets of the organization"
7. Answer again to the first receipt email with the same user as previously
8. Verify it answers to the initial ticket
=> fix: Expire cache of authorizations after 10s

src/Entity/Message.php, src/Service/DataImporter/DataImporter.php, tests/Service/DataImporter/DataImporterTest.php
N/A
1. Import an archive containing documents
2. Delete the documents in the database
3. Try to reimport the archive
4. Verify that the documents are attached back to their message
=> imp: Allow to reimport message documents

src/Entity/MessageDocument.php
https://github.com/Probesys/bileto/pull/896
1. Try to upload a MPEG audio file (e.g. .mp3)
2. Verify that it works
=> imp: Allow to upload MPEG audio files

src/Command/SeedsCommand.php, src/Form/Ticket/ActorsForm.php, src/Form/Ticket/QuickSearchForm.php, src/Form/TicketForm.php, src/Form/Type/ActorType.php, src/Repository/AuthorizationRepository.php, src/Repository/OrganizationRepository.php, src/Repository/UserRepository.php, src/Service/ActorsLister.php, tests/Controller/Tickets/ActorsControllerTest.php
https://github.com/Probesys/bileto/issues/902
1. Create a ticket and add a user as a requester and to the observers
2. Remove authorization of this user
3. Edit the list of actors of the ticket, don't change the users but submit the form
5. Verify that the user is still the requester / an observer of the ticket
=> fix: Make sure that actors of the ticket are not automatically removed from tickets after losing access to the organization

assets/stylesheets/components/messages.css, assets/stylesheets/components/timelines.css, templates/tickets/_time_spent.html.twig, templates/tickets/_timeline_event.html.twig, templates/tickets/_timeline_message.html.twig
N/A
1. Open a ticket
2. Click on the message date
3. Verify that the URL change with the anchor to the message, and that the screen scrolls to the message
=> imp: Add id/anchors on the timelines' items

.env, .github/workflows/tests.yml, CHANGELOG.md, Makefile, README.md, docker/development/docker-compose.yml, docs/administrators/deploy.md, env.sample
=> tec: Require PostgreSQL >= 13

.env, .github/workflows/tests.yml, CHANGELOG.md, README.md, docker/development/docker-compose.yml, docs/administrators/deploy.md, env.sample
=> tec: Require MariaDB >= 10.5

templates/tickets/_time_spent.html.twig, templates/tickets/_timeline_event.html.twig, templates/tickets/_timeline_message.html.twig
https://github.com/Probesys/bileto/issues/926
3. Add a message with spent time to the ticket
2. Change the status
4. Verify the date is visible in the timeline for the message, the spent time and the change event
=> imp: Display the date next to the time in the timeline

assets/javascripts/controllers/multiselect_controller.js, src/Form/Type/ActorType.php, src/Security/Authorizer.php, templates/form/bileto_theme.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/925
1. Add a user and an agent role to the same user in the same organization
1. Open a ticket in this organization
2. Verify that the actors in the select are grouped either by "Users" or "Agents"
3. Verify that the user is in the agent list
=> imp: Group the actors by their role type in the "select" lists

public/robots.txt
https://github.com/Probesys/bileto/issues/821
Check if http://localhost:8000/robots.txt  is accessible from browser
=> tec: Add a robots.txt file in public folder

.phpunit.xml.dist
=> dev: Add displayDetailsOnPhpunitDeprecations to PHPUnit config

src/Entity/User.php, src/MessageHandler/SendMessageEmailHandler.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
N/A
1. Create a ticket with three different requester, assignee and observer
2. As one of these actors, answer to the ticket
3. Verify that each of the other two actors receive an email where
- the "To" address contains the name and the email of the user
- the "From" address contains the name or email (if name is not set) of the author
=> tec: Send individual emails on notifications and add user names to email addresses

assets/stylesheets/components/alerts.css, assets/stylesheets/components/forms.css, migrations/Version20250522075934AddLoginDisabledAt.php, src/Controller/PasswordsController.php, src/Entity/User.php, src/Form/Password/ResetForm.php, src/Form/UserForm.php, src/MessageHandler/SendMessageEmailHandler.php, src/MessageHandler/SendReceiptEmailHandler.php, src/Repository/UserRepository.php, templates/emails/message.html.twig, templates/emails/message.txt.twig, templates/emails/receipt.html.twig, templates/emails/receipt.txt.twig, templates/users/_form.html.twig, templates/users/show.html.twig, tests/Controller/LoginControllerTest.php, tests/Controller/PasswordsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
Closes https://github.com/Probesys/bileto/issues/941
1. As a standard user login to Bileto in a private mode tab
1. As an admin, disable login for the user and verify that the information is displayed
2. As standard user, verify that you are no longer connected
3. As standard user, send an email to the support and verify that the receipt doesn't contain a link to the ticket
4. As agent, answer to the ticket and verify that the notification email doesn't  contain a link to the ticket
3. As standard user, try to reset your password
4. Verify the email is not sent
=> new: Allow to prevent users from logging in to the Web interface

src/Entity/Mailbox.php, src/Misc/AdditionalTranslations.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
N/A
1. Create a new mailbox
2. Verify that the encryption options are: SSL/TLS, StartTLS and None
=> fix: Fix Mailbox encryption options

src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, tests/Factory/MailboxEmailFactory.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
https://github.com/Probesys/bileto/issues/935
1. Send an email to the support address
2. Answer to the **sent** email, still sending to support
3. Check that the answer appears in the same ticket as the first message
=> new: Reference the incoming email Message-ID in messages

migrations/Version20250603134754AddAnonymizedToUsers.php, src/Controller/BaseController.php, src/Controller/Users/AnonymizationsController.php, src/Controller/Users/AuthorizationsController.php, src/Controller/UsersController.php, src/Entity/User.php, src/Form/User/AnonymizationForm.php, src/MessageHandler/SendMessageEmailHandler.php, src/MessageHandler/SendReceiptEmailHandler.php, src/Repository/EntityEventRepository.php, src/Repository/SessionLogRepository.php, src/Repository/UserRepository.php, src/Security/AppVoter.php, src/Service/UserService.php, templates/users/anonymizations/new.html.twig, templates/users/show.html.twig, tests/Controller/Tickets/MessagesControllerTest.php, tests/Controller/Users/AnonymizationsControllerTest.php, tests/Controller/Users/AuthorizationsControllerTest.php, tests/Controller/UsersControllerTest.php, tests/Service/ActorsListerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
Closes https://github.com/Probesys/bileto/issues/936
1. As a user, create a ticket and set yourself as the requester
2. As an admin, go to the list of users and anonymize the user
3. Check that the user is marked as anonymous in the admin
4. Check that the user is marked as anonymous in the ticket
=> new: Allow to anonymize the users

assets/javascripts/controllers/tinymce_controller.js, docker/production/Dockerfile, src/Controller/OrganizationsController.php, templates/organizations/_form.html.twig, templates/organizations/tickets/new.html.twig, templates/roles/_form.html.twig, templates/tickets/actors/edit.html.twig, templates/users/_form.html.twig, tests/Controller/OrganizationsControllerTest.php
Closes https://github.com/Probesys/bileto/issues/885
Closes https://github.com/Probesys/bileto/issues/944
Closes https://github.com/Probesys/bileto/issues/881
Closes https://github.com/Probesys/bileto/issues/962
Spell checking:
1. Start creating a ticket
2. Enter gibberish in the rich text editor
3. Verify the browser tells you the words don't exist
Contracts :
1. As an agent with orga creation admin permission and global orga contracts managing permission, create an organization
2. Verify that you're redirected to the "new contract" page of the organization
=> misc: Various improvements

README.md
https://github.com/Probesys/bileto/issues/766
N/A
=> doc: Add a note about compliance with the GDPR

.env, CHANGELOG.md, config/packages/framework.yaml, env.sample
=> tec: Allow to declare trusted proxies

composer.json, composer.lock, symfony.lock
Closes https://github.com/Probesys/bileto/issues/668
N/A
=> tec: Upgrade to PHPImap 6.2.0

migrations/Version20250604070746UpdateForeignKeysFromUser.php, src/Controller/UsersController.php, src/Entity/Authorization.php, src/Entity/Contract.php, src/Entity/EntityEvent.php, src/Entity/Label.php, src/Entity/Mailbox.php, src/Entity/MailboxEmail.php, src/Entity/Message.php, src/Entity/MessageDocument.php, src/Entity/Organization.php, src/Entity/Role.php, src/Entity/Team.php, src/Entity/TeamAuthorization.php, src/Entity/Ticket.php, src/Entity/TimeSpent.php, src/Entity/Token.php, src/Entity/User.php, src/Twig/TicketEventChangesFormatterExtension.php, templates/users/edit.html.twig, tests/Controller/UsersControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
=> feat: Allow to delete a user

templates/tickets/_search_form.html.twig
https://github.com/Probesys/bileto/issues/822
1. In the admin, make sure that you have no labels
2. On the tickets index page, verify the search form doesn't show the "labels" sections
=> Hide the "Filter by labels" section in the quick search form if there are no labels
