assets/stylesheets/application.css, assets/stylesheets/components/images.css, migrations/Version20221102091809CreateTicket.php, src/Controller/Organizations/TicketsController.php, src/Entity/Ticket.php, src/Twig/ViteTagsExtension.php
- Fix the columns names in the CreateTicket migration
- Make sure Turbo reload the page when the assets change
- Set images max-width to 100%
- Defer loading of the JavaScript script
- Move ticket title `trim()` in `setTitle()`
=> imp: various improvements

.gitignore, .vite/empty-assets-dir-plugin.js, README.md
- Keep track of the `public/assets/` folder
- Improve development setup documentation
- Invert `make docker-start` and `make db-setup` commands
- Indicate how to create a user
1. Setup a new environment
2. Follow the instructions from the README
3. Check the instructions work
=> tec: Fix initial setup

assets/stylesheets/_colors.dark.css, assets/stylesheets/_colors.light.css, assets/stylesheets/application.css, assets/stylesheets/components/badges.css, assets/stylesheets/pages/tickets-show.css, src/Entity/Ticket.php, templates/organizations/tickets/index.html.twig, templates/tickets/show.html.twig
Related to https://github.com/Probesys/bileto/issues/92
- Add colours for info (blue) and warnings (orange)
- Create a new `.badge` component
- Display status and priority with the badge component and change colours based on values of the properties
2. Change priority and status
3. Check the colours change
=> imp: Add colours to status and priority badges

assets/javascripts/application.js, assets/javascripts/controllers/new_ticket_controller.js, templates/organizations/tickets/new.html.twig
Related to https://github.com/Probesys/bileto/issues/91
- Create a Stimulus controller to manage the status in the new ticket form
- disable "new" status option if ticket is assigned (and set the "assignee" value)
- enable "new" status option if ticket is not assigned (and set the "new" value)
1. go to the new ticket form
2. select an assignee, check the status is set to "assigned" (and that the "new" option is disabled)
3. unselect the assignee, check the status is set back to "new"
=> imp: Autoselect status based on assignment in new ticket form

assets/stylesheets/components/messages.css, src/Service/DateTranslator.php, src/Twig/DateFormatterExtension.php, templates/organizations/tickets/index.html.twig, templates/tickets/show.html.twig
Related to https://github.com/Probesys/bileto/issues/76
- Create a class to translate dates accordingly to the current locale
- Create a Twig extension to use this translator
- Format the dates with the new Twig filters
- Adapt the layout (the strings are longer than before)
1. Open a ticket
2. Check that dates in the tickets list and on the ticket page are correctly formatted (day month year, hour:minute)
3. Check the dates are in a `<time>` element
=> imp: Improve format of dates

translations/messages.fr_FR.yaml
- Change "Assigné" to "Attribué à"
=> i18n: Improve wording of "assignee" in French

src/Controller/Tickets/TitleController.php, templates/tickets/show.html.twig, templates/tickets/title/edit.html.twig, tests/Controller/Tickets/TitleControllerTest.php, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/112
- Create a new controller dedicated to edit the tickets titles
- Add a button in the "actions" menu to open the rename modal
1. Open a ticket
2. Open the actions menu and click on "rename the ticket"
3. Change the title of the ticket
4. Verify the title has changed
=> new: Rename the tickets

assets/stylesheets/components/buttons.css, assets/stylesheets/components/forms.css, templates/tickets/show.html.twig, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/143
- Change button--ghost in button--anchor (color is changed to primary)
- Add a form to the "Actors" panel to assign an unassigned ticket to ourselves
1. Open a ticket, do not assign it
2. Click on "assign yourself"
3. Verify the ticket is now assigned to your current user
=> imp: Allow to self-assign a ticket

assets/stylesheets/components/buttons.css
Related to https://github.com/Probesys/bileto/issues/152
- Don't apply hover, focus and active styles on disabled buttons
- Desaturate colours, change cursor, remove outline on disabled buttons
1. Create an organization
2. While the request is being made, verify the button has a different style
=> imp: Add style to disabled buttons

config/services.yaml, tests/Command/Users/CreateCommandTest.php, tests/Controller/HomeControllerTest.php, tests/Controller/LoginControllerTest.php, tests/Controller/Organizations/TicketsControllerTest.php, tests/Controller/OrganizationsControllerTest.php, tests/Controller/PreferencesControllerTest.php, tests/Controller/Tickets/ActorsControllerTest.php, tests/Controller/Tickets/MessagesControllerTest.php, tests/Controller/Tickets/PriorityControllerTest.php, tests/Controller/Tickets/TitleControllerTest.php, tests/Controller/Tickets/TypeControllerTest.php, tests/Controller/TicketsControllerTest.php, tests/Factory/MessageFactory.php, tests/Factory/OrganizationFactory.php, tests/Factory/TicketFactory.php, tests/Factory/UserFactory.php
Related to https://github.com/Probesys/bileto/issues/160
- Move factories under tests/ folder
- Autowire / autoconfigure the App\Tests\Factory namespace
1. run the tests, check they pass
=> tec: Move factories under tests/ folder

config/packages/security.yaml, config/services.yaml, src/Controller/LoginController.php, src/Controller/PreferencesController.php, src/Controller/SessionController.php, src/Entity/User.php, src/EventSubscriber/LocaleSubscriber.php, src/Utils/Locales.php, templates/base.html.twig, templates/preferences/edit.html.twig, tests/Controller/SessionControllerTest.php, tests/SessionHelper.php, tests/Utils/LocalesTest.php
Related to https://github.com/Probesys/bileto/issues/86
- Rework how the supported locales are handled
- Calculate the best supported locale from the `Accept-Language` HTTP header
- Allow to change the session locale from the login form
1. Disconnect from Bileto and/or empty your cookies
2. Verify the locale corresponds to your browser preferences
3. Change the order of French and English languages in your browser preferences, and verify Bileto is generated with the correct locale
=> imp: Detect preferred language from browser

assets/stylesheets/application.css, templates/base.html.twig, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/95
- Add a link to the top of the page to give the focus to the main content (accessible with the keyboard)
1. load Bileto in your browser
2. navigate with the <kbd>tab</kbd> key to access the "skip to main content" anchor
3. press <kbd>enter</kbd>, then <kbd>tab</kbd> again
4. verify the focus is given to the first element of the main content
=> new: Add a "skip to main content" accessibility anchor

src/Controller/Organizations/TicketsController.php, src/Controller/Tickets/ActorsController.php, src/Controller/Tickets/MessagesController.php, templates/tickets/show.html.twig, tests/Controller/Organizations/TicketsControllerTest.php, tests/Controller/OrganizationsControllerTest.php, tests/Controller/PreferencesControllerTest.php, tests/Controller/SessionControllerTest.php, tests/Controller/Tickets/ActorsControllerTest.php, tests/Controller/Tickets/MessagesControllerTest.php, tests/Controller/Tickets/PriorityControllerTest.php, tests/Controller/Tickets/TitleControllerTest.php, tests/Controller/Tickets/TypeControllerTest.php, tests/SessionHelper.php
Related to https://github.com/Probesys/bileto/issues/161
- Add a `getSession` and a `generateCsrfToken` methods to `SessionHelper`
- Use `generateCsrfToken` in the tests in order to test controllers endpoints directly with `$client->request()`
- Add missing tests (e.g. for invalid values of selectboxes)
- Make sure to use the correct types when retrieving parameters from request
- Render correctly the errors on status when answering
How to test the feature manually: N/A
=> tec: Add more Controller tests

assets/stylesheets/application.css, assets/stylesheets/components/popups.css
- Increase font-size on mobile
- Increase padding of popups on mobile
1. verify it looks bigger!
=> imp: Improve sizes on mobile

src/Service/LocaleSorter.php, src/Service/OrganizationSorter.php
- Extract a LocaleSorter from OrganizationSorter
How to test the feature manually: N/A
=> tec: Extract a LocaleSorter from OrganizationSorter

docs/developers/roles.md, src/Controller/RolesController.php, src/Entity/Role.php, tests/Controller/RolesControllerTest.php
Related to https://github.com/Probesys/bileto/issues/88
- Rename the permission `admin:see:settings` in `admin:see`
How to test the feature manually: N/A
=> tec: Rename the admin:see:settings permission

src/Controller/PagesController.php, templates/organizations/tickets/index.html.twig, templates/pages/home.html.twig, tests/Controller/PagesControllerTest.php, translations/messages.en_GB.yaml, translations/messages.fr_FR.yaml
- Remove the useless sort when listing tickets
- Get the assigned tickets and display them on the home page
1. Assign some tickets to your user
2. Go to the home page
3. Check the tickets are shown on the home page
=> new: Add a home page to list assigned tickets

src/Controller/Users/AuthorizationsController.php, templates/users/authorizations/index.html.twig, tests/Controller/Users/AuthorizationsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml, translations/validators+intl-icu.en_GB.yaml, translations/validators+intl-icu.fr_FR.yaml
Related to https://github.com/Probesys/bileto/issues/88
- Add an endpoint to revoke the authorizations
- Add a button to revoke the authorizations in the list
1. Go to the authorizations list of a user, revoke an authorization → check it works
2. With super-admin authorization, go to your own authorization list → check the revoke button is hidden
3. With only `admin:manage:users` permission, go to the authorization list of a super-admin user → check the revoke button is hidden
=> new: Revoke users authorizations

assets/stylesheets/components/timelines.css, migrations/Version20230227142951AddHideEventsToUser.php, src/Controller/BaseController.php, src/Controller/PreferencesController.php, src/Entity/User.php, src/Service/TicketTimeline.php, templates/tickets/show.html.twig, tests/Controller/PreferencesControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/13
- add a new `hideEvents` property to User entity
- add a new endpoint in Preferences controller to change `hideEvents`
- to allow to redirect to an arbitrary page (i.e. any ticket page), this new endpoint takes a `from` parameter. This from is protected with a new `isPathRedirectable` added to the Base controller
- don't load the events in the TicketTimeline service if `hideEvents` is false
- add a button to toggle `hideEvents` at the bottom of the tickets timelines
- I've added it at the end to avoid to clutter the top of the page
- the drawback is that one has to scroll to the end of the page to hide all the events. If there are a lot of events, it can became annoying
- go to a ticket and make sure there are events
- click on "Hide history" → …
=> new: Allow to hide history in tickets timelines

.gitignore, .vite/empty-assets-dir-plugin.js
https://github.com/Probesys/bileto/issues/234
- remove the file `public/dev_assets/.keep`
- adapt the Vite plugin `empty-assets-dir` so it doesn't fail if the folder doesn't exist
N/A
=> misc: Don't track the dev_assets folder

assets/stylesheets/components/timelines.css, assets/stylesheets/pages/tickets-show.css, assets/stylesheets/utils/flow.css, assets/stylesheets/utils/rows.css, docs/developers/rows-and-grids.md, templates/base.html.twig, templates/organizations/tickets/index.html.twig, templates/organizations/tickets/new.html.twig, templates/pages/home.html.twig, templates/tickets/index.html.twig, templates/tickets/priority/edit.html.twig, templates/tickets/show.html.twig, templates/users/authorizations/new.html.twig, templates/users/index.html.twig
https://github.com/Probesys/bileto/issues/242
- remove margins from the `.row` class
- remove margins from the `.tickets-show .ticket__info` class
- apply `.flow` spaces to rows correctly (i.e. apply a margin-left instead of a margin-top on big screens or with `.row--always`)
- add `.flow*` classes to elements that already have a `.row` class
- navigate on Bileto either on big and small screens → check everything looks fine
=> tec: Apply .flow* classes to rows correctly

assets/javascripts/application.js
N/A
- listen for `turbo:frame-missing` to follow the redirections
- edit the priority of a ticket and submit → check the modal disappears and that the correct priority is displayed
=> fix: Follow the redirections after submitting forms in modals

src/Controller/Tickets/ActorsController.php, src/Controller/Tickets/MessagesController.php, src/Controller/Tickets/PriorityController.php, src/Controller/Tickets/StatusController.php, src/Controller/Tickets/TitleController.php, src/Controller/Tickets/TypeController.php, tests/Controller/Tickets/ActorsControllerTest.php, tests/Controller/Tickets/MessagesControllerTest.php, tests/Controller/Tickets/PriorityControllerTest.php, tests/Controller/Tickets/StatusControllerTest.php, tests/Controller/Tickets/TitleControllerTest.php, tests/Controller/Tickets/TypeControllerTest.php
N/A
- Check if the user has access to the ticket in the Tickets resources-controllers (i.e. under `Controllers/Tickets/*`)
- give a role with all the "update * of a ticket" permissions, but not "see all the tickets"
- go to the URL of a ticket which he has NO access → check you can't access the page
- do the same by appending `/actors/edit`, `/priority/edit`, `/status/edit` and `/title/edit` to the URL → check you can't access the pages
=> sec: Check access correctly in Tickets-related controllers

templates/organizations/tickets/index.html.twig, templates/tickets/_list.html.twig
N/A
- remove the `displayOrganization` option from the `tickets/_list.html.twig` partial
- go to the list of tickets of an organization → check the name of the orga appears in the list of tickets
=> imp: Always display the tickets organizations

config/packages/security.yaml
N/A
- add the /app.manifest URL to the public URLs
- while being disconnected, access http://localhost:8000/app.manifest
- check it displays the manifest
=> fix: Allow public access to the Web Manifest

Makefile
N/A
- remove the `--xdebug` option when running PHPStan
- run `make lint`, it should go faster than previously
=> tec: Disable XDebug when running PHPStan

assets/stylesheets/components/modal.css, templates/pages/advanced_search_syntax.html.twig
N/A
- add margin below the modal title
- remove the div from the advanced search syntax modal which was used to add space
- open the modals of the application → check there is space below the titles
=> imp: Add margin below the modal title

src/Controller/UsersController.php, src/Entity/User.php, templates/users/new.html.twig, tests/Controller/UsersControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/276
- add a password input to the "new user" form
- hash the password and set it to the user in the controller
- otherwise, set an empty string (instead of a random string)
- as an admin, go to the "new user" form
- create a user with a password
- check that you can login with this password
- create a user with no password
- check that you cannot login, even with an empty password
=> imp: Allow to set password when creating users

src/Controller/Organizations/TicketsController.php, src/Controller/TicketsController.php, src/SearchEngine/TicketFilter.php, templates/tickets/_search_form.html.twig, tests/SearchEngine/TicketFilterTest.php
https://github.com/Probesys/bileto/issues/8
- remove the "required" attribute from the advanced search form
- add a "mode" parameter to the Tickets#index controllers to remember the current mode
- check the values of the filters in TicketFilter
- search for an empty value in the advanced form → check it returns all the tickets
- search for a simple query (e.g. `email`) in advanced mode → check you stay in advanced mode after the submit
- search for `status:foo` in advanced mode → check the quick mode shows no filter
=> imp: Improve search

migrations/Version20230606132457AddOrganizationToUsers.php, src/Command/SeedsCommand.php, src/Controller/UsersController.php, src/Entity/User.php, templates/users/new.html.twig, tests/Controller/UsersControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/17
- add an organization relation to the User entity
- add a select box to the "new user" form to select an organization
- go to settings > users > new user
- create a user and set an organization
- with the psql command, check that the user has an organization (`SELECT * FROM users;`)
=> new: Allow to assign a user to an organization

config/packages/html_sanitizer.yaml, docs/developers/README.md, docs/developers/email-collector.md, src/Controller/MailboxesController.php, src/Entity/MailboxEmail.php, src/Message/CreateTicketsFromMailboxEmails.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/MessageHandler/FetchMailboxesHandler.php, src/Security/Authentication/UserToken.php, tests/Factory/MailboxEmailFactory.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
https://github.com/Probesys/bileto/issues/43
- add `html` and `body` to the blocked elements of the Html Sanitizer
- add a factory for the `MailboxEmail` entity
- create a `UserToken` to allow checking the permissions of an unauthenticated user
- set `lastErrorAt` when setting `lastError` of `MailboxEmail`
- add a new `ImportMailboxEmails` message + handler (+ tests) to import the `MailboxEmails` as `Tickets`
- create a mailbox as explained in the GreenMail documentation
- send an email to this mailbox with an email associated to an existing user, associated to an organization itself and with permission to create tickets in this organization
- click on "Collect the mailboxes"
- → check there is a new ticket named after your email subject
- → check there is no MailboxEmail in the database
=> new: Import MailboxEmails as Tickets

migrations/Version20230623122104AddLastErrorToMailbox.php, src/Controller/MailboxesController.php, src/Entity/Mailbox.php, src/MessageHandler/FetchMailboxesHandler.php, templates/mailboxes/index.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
- add fields `lastError` and `lastErrorAt` to `Mailbox
- set the errors during the test of the mailbox connection and when fetching mailboxes
- display the lastError in the list of mailboxes
- configure a mailbox with wrong information (e.g. wrong port)
- click on "test connection" → check the error is displayed below the mailbox
=> imp: Display Mailbox errors in the list

assets/javascripts/controllers/new_authorization_form_controller.js, src/Command/SeedsCommand.php, src/Controller/RolesController.php, src/Controller/Users/AuthorizationsController.php, src/Entity/Role.php, src/Repository/AuthorizationRepository.php, templates/roles/_role_form.html.twig, templates/users/authorizations/index.html.twig, tests/AuthorizationHelper.php, tests/Controller/RolesControllerTest.php, tests/Controller/Users/AuthorizationsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/273
https://github.com/Probesys/bileto/issues/147
- split the Role type `orga` in `orga:user` and `orga:tech`
- adapt the rest of the code to use these new types
- add radio buttons to the roles form to allow to select the orga type
- create a new role → check you can select either "user" or "tech"
- edit a role → check you can change the type
=> tec: Separate orga roles in user and tech roles

src/Controller/Organizations/TicketsController.php, src/Controller/Tickets/ActorsController.php, src/Controller/Tickets/FiltersController.php, src/Repository/UserRepository.php, src/Service/ActorsLister.php, templates/organizations/tickets/new.html.twig, templates/tickets/actors/edit.html.twig, templates/tickets/filters/edit_actors.html.twig, tests/Controller/Organizations/TicketsControllerTest.php, tests/Controller/Tickets/ActorsControllerTest.php, tests/Service/ActorsListerTest.php
https://github.com/Probesys/bileto/issues/273
- use the UsersSorter in the ActorsLister
- limit the actors lists to the users of the current organization
- limit the actors lists to the users of the accessible organizations
- allow to list users with either "user", "tech" or both roles
- open the lists of requesters (new ticket, edit actors and filter actors) → check only users of the current organization are listed
- open the lists of assignees (new ticket, edit actors and filter actors) → check only **tech** users of the current organization are listed
=> imp: Display only tech users in lists of assignees

src/MessageHandler/SendMessageEmailHandler.php
https://github.com/Probesys/bileto/issues/330
- return early when there is no recipient in email the notification system
- create a new ticket by email
- check in the logs of the worker that the `SendMessageEmail` message is handled successfully
=> fix: Don't try to send email if $recipients is empty

src/Controller/MailboxEmailsController.php, templates/mailboxes/index.html.twig, tests/Controller/MailboxEmailsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
- add a controller to delete mailbox emails
- add a link-button to delete mailbox emails in error on the mailboxes page
- send an email with an unknown sender
- collect the emails
- delete the email appearing on the page → check that the email disappears
=> new: Allow to delete a mailbox email in error

.env, Makefile, docker/docker-compose.yml, docs/developers/entity.md, docs/developers/setup.md
N/A
- uncomment the MariaDB service in the docker-compose.yml file
- rename the Docker database services
- assign profiles to the database services
- enable the given profile on `make docker-start`
- adapt the `DATABASE_URL` lines in the `.env` file
- run `make docker-start` → check it starts the pgsql service (and not the mariadb service)
- run `make docker-start DATABASE=mariadb` → check it starts the mariadb service (and not the pgsql service)
=> tec: Improve starting a MariaDB database in dev

docs/developers/notifications.md, src/Controller/BaseController.php, src/Controller/MailboxesController.php, src/Controller/Organizations/TicketsController.php, src/Controller/OrganizationsController.php, src/Controller/PreferencesController.php, src/Controller/ProfileController.php, src/Controller/RolesController.php, src/Controller/Tickets/MessagesController.php, src/Controller/Tickets/PriorityController.php, src/Controller/Tickets/StatusController.php, src/Controller/Tickets/TitleController.php, src/Controller/Tickets/TypeController.php, src/Controller/UsersController.php, src/Utils/ConstraintErrorsFormatter.php
N/A
- change the `BaseController::formatErrors` method into a static method in the `ConstraintErrorsFormatter` class
N/A
=> dev: Extract a ConstraintErrorsFormatter from BaseController

templates/profile/edit.html.twig
https://github.com/Probesys/bileto/pull/174
- remove the `required` attribute from the name field of the profile form
- go to the profile
- submit an empty name → check it works
=> fix: Allow no name to be entered in the profile

.env, docs/administrators/deploy.md, env.sample, src/Command/Ldap/SyncCommand.php, src/Message/SynchronizeLdap.php, src/MessageHandler/SynchronizeLdapHandler.php, src/Scheduler/DefaultScheduleProvider.php, src/Service/Ldap.php, tests/MessageHandler/SynchronizeLdapHandlerTest.php
https://github.com/Probesys/bileto/issues/168
- change the default value of env variable `LDAP_BASE_DN`
- rename env variable `LDAP_SEARCH_QUERY` in `LDAP_QUERY_SEARCH_USER`
- add env variables `LDAP_QUERY_LIST_USERS` and `LDAP_FIELD_IDENTIFIER`
- add a method to the Ldap service to list the users from the directory
- add a message + its handler to synchronize the users from LDAP
- schedule the message every 12h
- provide a console command to synchronize manually
- reset the database `make db-reset FORCE=true`
- run `./docker/bin/console app:ldap:sync`
- check in db (`./docker/bin/psql bileto`, `SELECT * FROM users`) that the user `dominique@example.com` exists
- run `./docker/bin/console debug:scheduler`
- check that the `SynchronizeLdap` message is scheduled every 12 hours
=> imp: Schedule the synchronization of LDAP

src/Controller/UsersController.php, src/Entity/User.php, src/MessageHandler/SynchronizeLdapHandler.php, templates/users/edit.html.twig, tests/Controller/UsersControllerTest.php, tests/MessageHandler/SynchronizeLdapHandlerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/168
- in admin, forbid changing name, email and password of users if ldapIdentifier is set
- add an input to change the ldapIdentifier
- when synchronizing, search users by their ldapIdentifier instead of email
- go to the settings > users
- edit charlie user → check that you can't change email, name or password
- empty the ldapIdentifier input → check that you can now change email, name and password
- set "charlie" back to the ldapIdentifier and run `./docker/bin/console app:ldap:sync`
- check that the information are back
=> imp: Allow admin to change the LDAP identifiers

src/Controller/TicketsController.php, tests/Controller/TicketsControllerTest.php
https://github.com/Probesys/bileto/issues/387
- when creating a ticket, redirect to the orga "new ticket" if the user can create tickets in its default organization
- with Alix user, click on the "New ticket" link on the homepage
- check that you're redirected to the the "Probesys" new ticket form
=> imp: Redirect if user can create ticket in its default organization

tests/Factory/MessageDocumentFactory.php
N/A
- default to "txt" extension when `MimeTypes` returns no extension in the `MessageDocumentFactory`
- N/A
=> misc: Handle unknown mimetype in MessageDocumentFactory

docs/developers/email-collector.md, src/Entity/MailboxEmail.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php
https://github.com/Probesys/bileto/issues/149
- Add a method to get PHPIMAP attachments from a `MailboxEmail`
- Save attachments as files and store them with `MessageDocumentStorage` in `CreateTicketsFromMailboxEmailsHandler.php`
- send an email to `support@example.com` with attachments
- check a ticket is created and that attachments are set in the message
=> imp: Import emails attachments as MessageDocuments

config/packages/html_sanitizer.yaml
https://github.com/Probesys/bileto/issues/149
- allow `width` on `img`
- insert an image in a message
- resize it
- check the size is respected in the final message
=> fix: Fix size of images in messages

.github/pull_request_template.md, assets/stylesheets/components/forms.css
https://github.com/Probesys/bileto/pull/437
- adapt the color of the editor background to match with the background of TinyMCE, depending on the color scheme
- add an item to the PR checklist to check that interface works in both light and dark modes
- switch to dark mode
- check that the editor looks fine
=> fix: Adapt the editor background to color scheme

src/Twig/DateFormatterExtension.php, templates/organizations/contracts/new.html.twig
N/A
- use `yyyy` pattern instead of `Y` when formatting the years
- set the date of your computer to "2023-01-01"
- start a new contract → check that the startAt input is set to "2023-01-01"
=> fix: Fix the year format in the Twig dateTrans filter

assets/javascripts/controllers/popup_controller.js, assets/stylesheets/components/popups.css, docs/developers/popups.md
N/A
This adds:
- automatic focus of the first element of a popup menu when opening a menu with the keyboard
- navigation in the menu with the arrows keys
- a new method to simply close the menu programmatically
- fix the selection of the popup__opener (typo)
- support for "radio" items in the menu
- open a popup menu with enter/space
- check the focus is given to the first element of the menu
- check you can navigate with arrows
- close the menu with escape
- check the focus is given back to the opener button
=> imp: Improve accessibility of popups

.gitignore
N/A
See commit
- Run the tests → check that `.phpunit.result.cache` is not created under `bin/ `
=> dev: Ignore .phpunit.result.cache only in the root folder

src/Controller/Tickets/ContractsController.php, src/Controller/Tickets/MessagesController.php, src/Entity/Ticket.php, src/Repository/TimeSpentRepository.php, src/Service/ContractBilling.php, templates/tickets/contracts/edit.html.twig, tests/Controller/Tickets/ContractsControllerTest.php, tests/Service/ContractBillingTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/35
- move the logic about charging time in a dedicated `ContractBilling` service
- add a checkbox to the form to edit a ticket's contract
- set unbilled times' contract when checking the checkbox
1. add times to a ticket without any contract
2. set the contract of the ticket and check the new checkbox
3. check that the times are now billed (and that the contract is already consumed)
=> new: Allow to bill unbilled times on contract change

templates/organizations/contracts/show.html.twig
https://github.com/Probesys/bileto/pull/473
- create a contract
- with a user which has the permission to see the contracts but not to manage them, go to the contract
- check the "renew" button is not appearing
=> fix: Hide renew contract button if permissions are not granted

.env, CHANGELOG.md, config/packages/routing.yaml, env.sample, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/Repository/MessageDocumentRepository.php
https://github.com/Probesys/bileto/issues/436
- configure a mailbox (see https://github.com/Probesys/bileto/blob/main/docs/developers/greenmail.md#in-bileto)
- send a mail to the mailbox with an image inlined in the content
- wait for the collector to fetch the email and create a ticket from it
- check that the image appears in the content
=> fix: Set correct inline attachments URLs in messages contents

CHANGELOG.md, composer.json, composer.lock, docker/Dockerfile, docker/production/Dockerfile, src/Entity/MailboxEmail.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php
https://github.com/Probesys/bileto/issues/488
- configure the email address alix@example.com in both Thunderbird and Gnome Evolution if possible (in order to send emails to support@example.com with both email clients)
- create a file named `café.txt` (ex. `echo 'Hello World' > café.txt`)
- in each email clients:
- send an HTML email containing at least an accent in the subject and in the body, and attach the file `café.txt` to it
- collect the emails from the support@example.com mailbox
- check that the subject, the body and the filename of the attachment are displayed correctly in the ticket (note: the attachment sent with Evolution should appear as `caf?.txt` due to a bug in PHP-IMAP, see https://github.com/Webklex/php-imap/issues/459)
- send an empty email (choose whatever subject you …
=> fix: Fix various encoding issues in emails

assets/stylesheets/components/messages.css
N/A
1. send an email with a long line in a `pre` element
2. fetch the emails → check the line is wrapped and doesn't extend the message, breaking the interface
=> fix: Wrap pre elements in messages contents

translations/messages+intl-icu.en_GB.yaml
https://github.com/Probesys/bileto/issues/498
- Connect yourself
- Go to preferences
- Change the language in English
- Update a ticket (Add or change any informations)
- Go to .../tickets
- Check that there is no orphan parenthesis at the end of "Incident updated on..."
=> i18n: Remove the Orphan parenthesis from the incident_updated_on key

Makefile, assets/stylesheets/components/alerts.css, src/Controller/Users/AuthorizationsController.php, src/Controller/UsersController.php, templates/users/authorizations/index.html.twig, templates/users/edit.html.twig, tests/Controller/UsersControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/566
1. create a user and set them a default organization
2. check that you're redirected to the new authorization of the user, and that the default organization is selected
3. before submitting the form, return to the list of the authorizations
4. check that there's a warning about missing permission for the user in their default organization
5. return to the list of the users, and edit the new user
6. check there's a warning about the missing permission on the default organization field
7. click on the link in the warning
8. check that you're redirected to the new authorization form and that the default organization is selected
9. give the user an authorization (the role must be able to create a ticket)
10. check that you're redirected to the …
=> imp: Warn if user has no permission in their default organization

migrations/Version20240201145738RenameContractBillingIntervalToTimeAccountingUnit.php, src/Controller/Tickets/ContractsController.php, src/Controller/Tickets/MessagesController.php, src/Entity/Contract.php, src/Entity/Ticket.php, src/Form/Type/ContractType.php, src/Service/ContractTimeAccounting.php, templates/contracts/_form.html.twig, templates/contracts/show.html.twig, templates/tickets/_timeline_time_spent.html.twig, templates/tickets/contracts/edit.html.twig, tests/Controller/Organizations/ContractsControllerTest.php, tests/Controller/Tickets/ContractsControllerTest.php, tests/Controller/Tickets/MessagesControllerTest.php, tests/Factory/ContractFactory.php, tests/Service/ContractTimeAccountingTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
Resolve https://github.com/Probesys/bileto/issues/523
- Create a contract → check that the "billing interval" field is renamed to "Time accounting unit" and the description is adapted (set the value to 30)
- Check the time accounting unit is displayed on the contract page
- Set the contract to a ticket → check that the checkbox is rephrased to "Include unaccounted time in the contract"
- Add an answer and spend time (less than 30 minutes, e.g. 10 minutes)
- Check the time is displayed as "10 minutes spent (30 minutes accounted) "
=> imp: Change wording from billed/charged to accounted time

docker/development/docker-compose.yml, docs/administrators/docker.md
N/A
1. Run `./docker/bin/php --version`
2. Check there is no warning (`WARN[0000] /path/to/bileto/docker/development/docker-compose.yml: version is obsolete`)
=>  dev: Remove the warning about docker-compose.yml version

src/Twig/HoursFormatterExtension.php, templates/tickets/_timeline_time_spent.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
#505 
- create a contract with a billing interval of 30 minutes
- attach the contract to a ticket
- answer to the ticket with spent time (e.g. 70 minutes)
- check the time is displayed as "1h 10m spent (1h 30m charged)"
=> 505 display time spents in the ticket timeline formatted as hours

src/Entity/Contract.php, templates/contracts/show.html.twig, templates/organizations/contracts/index.html.twig, templates/tickets/show.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/502
1. Create a contract
2. Attach a ticket to the contract
3. Answer to the ticket with time spent
4. Check on the right column that the percentage of consumption of the contract is displayed
5. Go to the contract page, check the percentage is displayed as well
6. Go to the list of contracts, check the percentage is displayed as well
=> imp: Display contract hours consumed as a percentage

templates/contracts/show.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/503
1. Create a contract
2. Check there is a default alert on the progress bar of the date
3. Check the label of the alert indicates the number of days before the end of the contract
4. Hover the label and check it indicates the actual date of the alert
=> imp: Display the contract date alert as a number of days

docs/developers/greenmail.md, src/Controller/AdminController.php, templates/admin.html.twig, templates/admin/index.html.twig, templates/base.html.twig, templates/mailboxes/edit.html.twig, templates/mailboxes/index.html.twig, templates/mailboxes/new.html.twig, templates/roles/edit.html.twig, templates/roles/index.html.twig, templates/roles/new.html.twig, templates/teams/agents/new.html.twig, templates/teams/authorizations/new.html.twig, templates/teams/edit.html.twig, templates/teams/index.html.twig, templates/teams/new.html.twig, templates/teams/show.html.twig, templates/users/authorizations/index.html.twig, templates/users/authorizations/new.html.twig, templates/users/edit.html.twig, templates/users/index.html.twig, templates/users/new.html.twig, tests/Controller/AdminControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
N/A
- login with a user who has admin access
- verify that "Settings" is now "Admin"
- navigate in different parts of the admin → verify the breadcrumb displays "Admin" instead of "Settings"
=> imp: Rename global "Settings" to "Admin"

templates/tickets/show.html.twig
https://github.com/Probesys/bileto/pull/628
- as an agent with all permissions, go to (or create) a ticket on which you're neither requester, nor assignee
- verify that you can add "spent time" and select "Confidential answer" (and post the answer)
- assign the ticket to yourself
- verify that you can select "Solution" (and post it)
- verify that you can still select "Confidential answer" and add "spent time"
=> fix: Display answer agent menu to all agents of the organization

migrations/Version20240619153400AddDomainsToOrganization.php, src/Controller/OrganizationsController.php, src/Entity/Organization.php, src/Form/Type/OrganizationType.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/Repository/OrganizationRepository.php, src/Utils/Url.php, src/Validator/OrganizationDomain.php, src/Validator/OrganizationDomainValidator.php, templates/organizations/_form.html.twig, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php, tests/Utils/UrlTest.php, translations/errors+intl-icu.en_GB.yaml, translations/errors+intl-icu.fr_FR.yaml, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/645
1. Create two organizations: associate the domain `example.com` to the first, and `*` to the other
2. Configure two email accounts (https://github.com/Probesys/bileto/blob/main/docs/developers/greenmail.md#with-thunderbird-or-any-external-mail-client): one with an existing user such as `alix@example.com` (make sure to use this domain!), and another one which doesn't exist (e.g. `dominique@example.org` → make sure the domain is different from the first one!)
3. Make sure the first user doesn't have a "default" organization, but can create tickets in the organization that handles the `example.com` domain
4. Send an email with both accounts to `support@example.com` and fetch the mailboxes
5. Verify that a new ticket is opened by …
=> new: Allow to associate organizations to email domains

docs/developers/email-collector.md, src/Entity/MailboxEmail.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, tests/Factory/MailboxEmailFactory.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
N/A
- make sure there are two users: `alix@example.com` and `charlie@example.com`
- setup the two emails accounts [in a webclient](https://github.com/Probesys/bileto/blob/a2318f6d9653c1aff2adf1e4b6c83a31933a0c51/docs/developers/greenmail.md#with-thunderbird-or-any-external-mail-client)
- send an email with `alix@example.com` to `support@example.com` BUT set "reply to" to `charlie@example.com`
- collect the mailbox
- verify a ticket is opened and the requester is `alix@example.com`
=> sec: Don't use the Reply-To header to get the requester

src/Controller/Organizations/TicketsController.php, src/Controller/TicketsController.php, src/Repository/LabelRepository.php, src/SearchEngine/QueryBuilder/TicketQueryBuilder.php, src/SearchEngine/TicketFilter.php, templates/organizations/tickets/index.html.twig, templates/pages/advanced_search_syntax.html.twig, templates/tickets/_search_form.html.twig, templates/tickets/index.html.twig, tests/Controller/Tickets/FiltersControllerTest.php, tests/SearchEngine/QueryBuilder/TicketQueryBuilderTest.php, tests/SearchEngine/TicketFilterTest.php, tests/SearchEngine/TicketSearcherTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/283
1. Make sure your user has the permission to create labels and update tickets' labels
2. Create at least 2 labels in the admin
3. Attach a ticket to the first label, another one to the other, and a last ticket to both labels
4. In the tickets list, filter only by the first label → verify that the first and third tickets appear
4. Filter only by the second label → verify that the second and third tickets appear
4. Filter by both labels → verify that only the third ticket appears
=> new: Allow to search and filter tickets by labels

src/SearchEngine/QueryBuilder/TicketQueryBuilder.php, tests/SearchEngine/QueryBuilder/TicketQueryBuilderTest.php, tests/SearchEngine/TicketSearcherTest.php
https://github.com/Probesys/bileto/pull/689
- Create three tickets: one assigned to your user, one unassigned, one assigned to another user
- Search for `assignee:@me`
- Verify that you see only your ticket
- Search for `NOT assignee:@me`
- Verify that you see the others tickets
=> fix: Fix search with "NOT assignee" for unassigned tickets

.github/pull_request_template.md, CONTRIBUTING.md, docs/developers/import-data.md, src/Entity/Team.php, src/Service/DataImporter/DataImporter.php, tests/Service/DataImporter/DataImporterTest.php
N/A
1. Create an archive to import following the spec and containing a team
2. Call `console app:data:import data.zip`
3. Verify that the team is imported
Note that teams' agents cannot be imported yet. This is because we would need to associate the teamAuthorization to users' authorizations. That's too complicated to handle for now. The actual solution is to let the admins add the agents manually in the teams at the end of the import.
=> imp: Allow to import teams

tests/Service/DataImporter/DataImporterTest.php
N/A
- run `make test FILE=tests/Service/DataImporter/DataImporterTest.php`
- verify that Testdox doesn't show any warning
=> dev: Fix some PHPUnit Testdox warnings

migrations/Version20240814075419AddObserversToOrganization.php, src/Controller/Organizations/ObserversController.php, src/Controller/Organizations/TicketsController.php, src/Entity/Organization.php, templates/organizations/users/index.html.twig, tests/Controller/Organizations/ObserversControllerTest.php, tests/Controller/Organizations/TicketsControllerTest.php, translations/errors+intl-icu.en_GB.yaml, translations/errors+intl-icu.fr_FR.yaml, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/39
- In an organization, go to the list of users
- Add a user as an observer
- Create a ticket
- Verify that the user is an observer of the ticket
=> imp: Allow to set default organization' observers

src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
https://github.com/Probesys/bileto/issues/39
https://github.com/Probesys/bileto/pull/702
- In an organization, go to the list of users
- Add a user as an observer
- Create a ticket by email with a user in the same organization as the observer
- Verify that the observer is set on the ticket
=> fix: Set ticket's default observers when opened by email

CHANGELOG.md, env.sample, src/Command/SeedsCommand.php, src/Controller/LoginController.php, src/Controller/PagesController.php, src/Controller/PreferencesController.php, src/Controller/SessionController.php, src/Entity/User.php, src/EventSubscriber/LocaleSubscriber.php, src/Service/Locales.php, src/Service/Sorter/LocaleSorter.php, src/Service/UserCreator.php, tests/Service/LocalesTest.php
https://github.com/Probesys/bileto/issues/530
1. Set `APP_DEFAULT_LOCALE=fr_FR` in your `.env.local` file
2. Reset the database `make db-reset FORCE=true`
3. Login with `alix@example.com` and verify that their locale is French
4. Create a user with CLI `./docker/bin/console app:user:create`
5. Login with this user and verify that their locale is French
=> tec: Allow to change the default locale globally

Makefile, docs/administrators/deploy.md, docs/developers/setup.md
N/A
- run `make db-reset FORCE=true NO_SEED=true`
- create a user `./docker/bin/console app:users:create`
- login and verify that there is no data (especially no roles) except your users and the super-admin role
=> tec: Allow to setup/reset the database without the seeds

docs/developers/roles.md, src/Command/SeedsCommand.php, src/Command/Users/CreateCommand.php, src/Controller/TicketsController.php, src/Controller/Users/AuthorizationsController.php, src/Controller/UsersController.php, src/Form/Type/OrganizationType.php, src/Form/UserForm.php, src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/Repository/AuthorizationRepository.php, src/Repository/OrganizationRepository.php, src/Security/Authorizer.php, src/Service/TeamService.php, src/Service/UserCreator.php, src/Service/UserService.php, templates/users/_form.html.twig, templates/users/show.html.twig, tests/AuthorizationHelper.php, tests/Controller/Users/AuthorizationsControllerTest.php, tests/Controller/UsersControllerTest.php, tests/Security/AuthorizerTest.php, tests/Service/ActorsListerTest.php, tests/Service/UserServiceTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/747
1. Create a user
2. Verify that you cannot select an organization at this step
3. Verify that you're redirected to the authorization form
4. Give a "user authorization" to the user on a specific organization
5. Login with this user
6. Verify that you can create a ticket with this user
7. As an admin, edit the user
8. Verify that you can now select a default organization and that only one organization is selectable
=> Determine the default user's organization from their authorizations

assets/javascripts/controllers/timeline_controller.js
N/A
1. Create a ticket and post some other answers with big images
2. Refresh the browser tab
3. Verify that the timeline bar on the left goes to the last element of the timeline
=> fix: Fix the timeline bar height

templates/tickets/show.html.twig
https://github.com/Probesys/bileto/issues/275
1. create a ticket and close it without assigning an agent to it
2. verify that the "unassigned" label cannot be clicked
=> fix: Don't show "unassigned buttons" if ticket is closed

src/Repository/AuthorizationRepository.php, tests/MessageHandler/SynchronizeLdapHandlerTest.php
https://github.com/Probesys/bileto/issues/763
1. Create a default user role
2. Setup a LDAP server
3. Make sure the LDAP users' emails are not handled by any organization (e.g. no `*` domain)
4. Synchronize the LDAP users
5. Verify that the synchronization doesn't fail
=> fix: Fix LDAP sync when creating new users

Makefile, docker/development/docker-compose.yml, docs/developers/setup.md
N/A
1. Run the dev env with `make docker-start`
2. Verify that the LDAP container is started
=> dev: Enable LDAP server by default in dev env

Makefile, docker/bin/composer, docker/bin/console, docker/bin/npm, docker/bin/php, docker/bin/psql, docker/development/docker-compose.yml
N/A
1. run `make docker-start`
2. run the commands under `./docker/bin/`
3. verify they all use the Docker Compose project name "bileto" (the Docker containers must be prefixed by `bileto-`)
=> dev: Declare the Docker Composer project name in docker-compose.yml

migrations/Version20241119150300AddMessageToTimeSpent.php, src/Controller/Tickets/MessagesController.php, src/Entity/TimeSpent.php, src/Service/TicketTimeAccounting.php, tests/Controller/Tickets/MessagesControllerTest.php
https://github.com/Probesys/bileto/issues/612
1. Answer with a message containing the string `#oncall` and add time spent
2. In the database (`./docker/bin/psql bileto`), run:
```sql
SELECT u.email, SUM(ts.real_time)
FROM time_spent ts, users u, message m
WHERE ts.created_by_id = u.id
AND ts.message_id = m.id
AND m.content LIKE '%#oncall%'
AND ts.created_at >= '2024-11-01'
AND ts.created_at < '2024-12-01'
GROUP BY u.email;
```
3. verify it shows the time spent
=> tec: Associate time spent with corresponding message

src/Controller/UsersController.php, templates/users/show.html.twig, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/795
1. Make sure no organization has "domains"
1. Create a user without authorization
2. Verify the user has no "Organization" on its page
3. Add an authorization to the user on a specific organization
5. Verify the user has the corresponding organization on its page (marked as "Automatic")
4. Add the domain of the user to another organization
5. Verify the user has the corresponding organization on its page (marked as "Automatic")
6. Force the user's organization with the edit form
5. Verify the user has the corresponding organization on its page
=> imp: Display the user organization automatically calculated

src/MessageHandler/SynchronizeLdapHandler.php, src/Security/Authorizer.php, src/Service/UserCreator.php, tests/MessageHandler/SynchronizeLdapHandlerTest.php, tests/Service/UserCreatorTest.php
N/A
- make sure LDAP is enabled (`LDAP_ENABLED=true` should be in your `.env.local` file)
- reset the database without seeds: `make db-reset FORCE=true NO_SEED=true`
- create the user Charlie Gature: `./docker/bin/console app:users:create --email=charlie@example.com --password=secret`
- synchronize the LDAP data: `./docker/bin/console app:ldap:sync`
- verify it doesn't fail
- login with `charlie` / `secret`
- verify that you can login and that the user's LDAP identifier is `charlie` in the admin
=> fix: Find LDAP user by email if identifier is not set yet

src/Entity/Contract.php
N/A
1. Create a new contract
2. Verify that the default value for the "time accounting unit" is 30
=> imp: Set the default value of Contract time accounting unit to 30

templates/organization.html.twig
N/A
1. login as a user with no access to contracts nor users
2. go to an organization
3. verify that you don't see the organization sub-menu
=> imp: Hide the organization submenu if user can only see tickets

translations/messages+intl-icu.fr_FR.yaml
N/A
1. Verify on the home page and in the tickets lists that "Vos tickets assignés" has been changed to "Vos tickets attribués"
2. Verify on the organization settings page and in the team form that "équipe assignée" has been changed to "équipe attribuée"
=> fix: Change "assigné" to "attribué" in the French translation

src/Twig/HoursFormatterExtension.php, translations/messages+intl-icu.fr_FR.yaml
N/A
1. Set the interface in French
1. Open a ticket with a user who can see both accounted and real spent time
2. Verify the ticket has no spent time
3. Verify that the total time is "0 minute"
=> fix: Fix display of total spent time when equal to 0 in French

templates/organizations/contracts/index.html.twig
N/A
1. Go to the list of contracts of an organization
2. Change their order with the "sort" button
3. Verify you're still in the list of contracts of the organization
=> fix: Stay in organization when changing contracts order

src/MessageHandler/SendReceiptEmailHandler.php, tests/Controller/Organizations/TicketsControllerTest.php
https://github.com/Probesys/bileto/issues/905
1. Create a ticket and set a requester different than the current user
2. Verify that the requester gets only the "message" notification
=> imp: Send the receipt only if the requester created the ticket

src/Repository/TeamRepository.php, src/SearchEngine/Ticket/QueryBuilder.php, templates/pages/advanced_search_syntax/tickets.html.twig, tests/SearchEngine/Ticket/SearcherTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/898
1. Create two teams
2. Assign a ticket to each team
3. Search for `team:a` and `-team:a`
4. Search for `has:team` and `no:team`
5. Verify that the found tickets correspond to their team
=> imp: Allow to search tickets by team with the advanced syntax

.env, config/packages/sentry.yaml, docs/administrators/deploy.md, env.sample
https://github.com/Probesys/bileto/issues/915
1. Create a Sentry project
2. Setup Sentry locally and set `SENTRY_SEND_DEFAULT_PII=true`
3. Set the environment to `prod` and run `./docker/bin/console c:c`
4. Generate an error (e.g. 404 error)
5. Verify that the error appears in Sentry and that it contains IP, username, etc.
=> tec: Allow administrators to send PII to Sentry

src/Controller/TicketsController.php, src/Security/Authorizer.php, templates/tickets/index.html.twig, templates/tickets/new.html.twig, tests/Controller/TicketsControllerTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
https://github.com/Probesys/bileto/issues/924
1. Create two users: one must be able to open tickets in several organizations, the other must be able to open tickets in only one organization
2. With the first user, go to the global tickets list and click on "New ticket"
3. Verify that a modal allows to select the organization
4. With the other user, go to the global tickets list and click on "New ticket"
5. Verify that you're redirected to the "new ticket" form of the user's default organization
=> imp: Allow to select the organization when opening a ticket from the global list

src/TicketActivity/LifecycleSubscriber.php, tests/Controller/Tickets/MessagesControllerTest.php
https://github.com/Probesys/bileto/issues/903
1. Grant authorization to a simple user to access all the tickets of an organization
1. Create a ticket in this organization, without setting the user as requester or even observer
2. As an agent, resolve the ticket
3. As a user, answer to the ticket
4. Verify the ticket is now "in progress" and that the solution has been removed
5. Do the same by email
=> imp: Reopen resolved ticket if answerer is not an agent

src/SearchEngine/Ticket/QuickSearchFilter.php, src/SearchEngine/Ticket/QuickSearchFilterBuilder.php, tests/Controller/Tickets/QuickSearchesControllerTest.php, tests/SearchEngine/Ticket/QuickSearchFilterBuilderTest.php
https://github.com/Probesys/bileto/issues/834
1. Create two labels
2. Set one label on a first ticket and both labels to another ticket
3. In the "quick search form", search for both labels
4. Verify that it returns the two tickets
=> imp: Change quick search so it searches for tickets with any label

.env, .env.dev, .env.test, config/packages/sentry.yaml, docs/developers/README.md, docs/developers/environment-files.md, docs/developers/setup.md, env.sample, src/Service/Ldap.php, src/Service/Locales.php
While working on https://github.com/Probesys/bileto/pull/916, I've realized that I could greatly improve the handling of environment variables in the application, especially to avoid the weird `default:` env var processor. The idea was to declare all the "production" environment variables in the `.env` file.
Then, I wasn't happy with the default values being those for the development environment. The `.env` variables are now suitable for production. The only exception is the `APP_ENV` variable which is set to `dev` in order to ease the workflow in development.
The development variables are now declared in a `.env.dev` file. This implied to copy some of them in the `.env.test` as well.
The consequences are:
1. production is not setup anymore with default (but not working) `APP_SECRET`, …
=> dev: Reorganize and document the env files

src/MessageHandler/CreateTicketsFromMailboxEmailsHandler.php, src/Utils/Time.php, tests/MessageHandler/CreateTicketsFromMailboxEmailsHandlerTest.php
N/A
1. Stop the worker
2. Send an email to support
3. Wait for more than a minute
4. Collect the emails manually
5. Verify that the ticket is created at "now", but the first message's date is the email's date
=> Use the email's date as message's creation date

src/Twig/TicketEventChangesFormatterExtension.php, tests/Twig/TicketEventChangesFormatterExtensionTest.php, translations/messages+intl-icu.en_GB.yaml, translations/messages+intl-icu.fr_FR.yaml
N/A
1. Make sure to have two organizations and one ticket in one of them
2. Transfer the ticket to the other organization, then back to the initial organization
3. Delete the organization that doesn't have the ticket
4. Open the ticket and verify that the ticket has been transferred to and from a "deleted organization"
=> fix: Fix transfer event when an organization has been deleted
